### ISSUE TITLE
Check for 0.0.0.0/0 in security group not working

### ISSUE THREAD

**Issue by vennemp** [aws-cloudformation/cloudformation-guard#102]
Struggling with the correct syntax to prevent 0.0.0.0/0 from appearing in security group rules

AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp != '0.0.0.0/0'

```yaml
  WindowsStandardSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref WindowsStandardSG
      VpcId: !Ref VPC
      SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: '-1'
            Description: "Test"
```
```
    CompoundRule {
        compound_type: AND,
        raw_rule: "AWS::EC2::SecurityGroup SecurityGroupIngress.*.CidrIp != \'0.0.0.0/0\'",
        rule_list: [
            SimpleRule(
                Rule {
                    resource_type: "AWS::EC2::SecurityGroup",
                    field: "SecurityGroupIngress.0.CidrIp",
                    operation: RequireNot,
                    value: "\'0.0.0.0/0\'",
                    rule_vtype: Value,
                    custom_msg: None,
                },
            ),
        ],
    },
)'
2020-11-12 17:46:01,401 INFO  [cfn_guard] Checking [WindowsStandardSG] which is of type "AWS::EC2::SecurityGroup"
2020-11-12 17:46:01,401 INFO  [cfn_guard] Result: PASS
2020-11-12 17:46:01,401 INFO  [cfn_guard] Applying rule 'CompoundRule(
    CompoundRule {
        compound_type: AND,
        raw_rule: "AWS::EC2::SecurityGroup SecurityGroupEgress.*.CidrIp != \'0.0.0.0/0\'",
        rule_list: [],
    },
)'
2020-11-12 17:46:01,401 INFO  [cfn_guard] All CloudFormation resources passed
```

This groups should fail...

[WindowsStandardSG] failed because it does not contain the required property of [SecurityGroupIngress24.CidrIp]
[WindowsStandardSG] failed because it does not contain the required property of [SecurityGroupEgress.25.CidrIp]
[WindowsStandardSG] failed because it does not contain the required property of [SecurityGroupEgress.26.CidrIp]

Not this is a blo
