### ISSUE TITLE
Support JSON-string formatted objects

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cloudformation-guard#11]
Given the rule:

```
AWS::IAM::Role AssumeRolePolicyDocument.Statement.*.Principal.Service.* == lambda.amazonaws.com
```

The following template correctly flags an issue:

```
Resources:
  LambdaRoleHelper:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - notlambda.amazonaws.com
```

However if I format the template to perform the same function, but using the JSON syntax like so:

```
Resources:
  LambdaRoleHelper:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "notlambda.amazonaws.com"
                ]
              }
            }
          ]
        }
```

The ruleset does not pick up on the violation.
