### ISSUE TITLE
[BUG] Wildcard Semantics 

### ISSUE THREAD

**Issue by gitFurious** [aws-cloudformation/cloudformation-guard#117]
**Describe the bug**

The cfn-guard README includes a section on [Wildcard Semantics](https://github.com/aws-cloudformation/cloudformation-guard/tree/master/cfn-guard#wildcard-semantics) where two example rules are shown:

1. ... means "**At least one item that matches those wildcards should match that value**" and is executed as a set of OR rules.
2. ... means "**None of the items that those wildcards match should match that value**" and is executed as a set of AND rules.

How do I write a rule that is effectively "**_ALL_ of the items that those wildcards match should match that value**"?

**To Reproduce**
For example, I attempted this rule against a (contrived) template and it passed where I would like to see it fail.

Rule: `AWS::EC2::LaunchTemplate LaunchTemplateData.BlockDeviceMappings.*.Ebs.Encrypted == true`
Template: 

```
---
AWSTemplateFormatVersion: "2010-09-09"
 
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        BlockDeviceMappings:
          - Ebs:
              Encrypted: true
          - Ebs:
              Encrypted: false
```

Inverting the rule appears to fix it, except it can be bypassed (and the rule passes):

Rule: `AWS::EC2::LaunchTemplate LaunchTemplateData.BlockDeviceMappings.*.Ebs.Encrypted != false`
Template: 
```
---
AWSTemplateFormatVersion: "2010-09-09"
 
Parameters:
  Encrypted:
    Type: String
    Default: false
 
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        BlockDeviceMappings:
          - Ebs:
              Encrypted: true
          - Ebs:
              Encrypted: !Ref Encrypted
```

**Expected behavior**
A rule that I can develop that allows matching all items in a list.

**Comment by jotompki** [comment]
Related to #5 . Our current RFC #115  addresses this. We plan to support this "ALL" check for wildcards in addition to the "ANY" check in the current version of the language.

**Comment by dchakrav-github** [comment]
Guard 2.0 by default matches ALL semantics. You can use `SOME` to match at-least-one. Here are the rules for these 

```
rule all_matches {
    AWS::EC2::LaunchTemplate Properties {
        LaunchTemplateData.BlockDeviceMappings.*.Ebs.Encrypted == true
    }
}

rule some_matches {
    AWS::EC2::LaunchTemplate Properties {
        some LaunchTemplateData.BlockDeviceMappings.*.Ebs.Encrypted == true
    }
}
```

and here is the unit test for this
```
---
- input:
    Resources:
      LaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
          LaunchTemplateData:
            InstanceType: t2.micro
            BlockDeviceMappings:
              - Ebs:
                  Encrypted: true
              - Ebs:
                  Encrypted: false
  expectations:
      rules:
          all_matches: FAIL
          some_matches: PASS
- input:
    Resources:
      LaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
          LaunchTemplateData:
            InstanceType: t2.micro
            BlockDeviceMappings:
              - Ebs:
                  Encrypted: true
              - Ebs:
                  Encrypted: true
  expectations:
      rules:
          all_matches: PASS
          some_matches: PASS
- input:
    Resources:
      LaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
          LaunchTemplateData:
            InstanceType: t2.micro
            BlockDeviceMappings:
              - Ebs:
                  Encrypted: true
              - Ebs:
                  Encrypted: 
                    Ref: Param
  expectations:
      rules:
          all_matches: FAIL # FAILs as bool is not comparable with struct
          some_matches: PASS
- input:
    Resources:
      LaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties:
          LaunchTemplateData:
            InstanceType: t2.micro
  expectations:
      rules:
          all_matches: FAIL
          some_matches: FAIL
```

Sample test run
```bash
$ cfn-guard-2 test -r ec2-lt-v2.guard -t ec2-lt-tests.yaml 
PASS Expected Rule = all_matches, Status = FAIL, Got Status = FAIL
PASS Expected Rule = some_matches, Status = PASS, Got Status = PASS
PASS Expected Rule = all_matches, Status = PASS, Got Status = PASS
PASS Expected Rule = some_matches, Status = PASS, Got Status = PASS
PASS Expected Rule = all_matches, Status = FAIL, Got Status = FAIL
PASS Expected Rule = some_matches, Status = PASS, Got Status = PASS
PASS Expected Rule = all_matches, Status = FAIL, Got Status = FAIL
PASS Expected Rule = some_matches, Status = FAIL, Got Status = FAIL
```
