### ISSUE TITLE
Bug(OR Clause): Or Clauses Don't Evaluate Correctly

### ISSUE THREAD

**Issue by AjkayAlan** [aws-cloudformation/cloudformation-guard#135]
## The Problem

I have a stack which creates both an S3 bucket for a static website, and an S3 bucket where logs will be sent to. So, the "logging" bucket can't have a logging config, though it generally will have an `AccessControl` of `LogDeliveryWrite`. So I need to ensure that all my "normal" buckets have logging, but the logging buckets won't.

I can't seem to get a super nice rule that works, and I am wondering if this is because I am fighting a bug, or doing something wrong.

## Setup:
Given I have the following test:

```
- input:
    Resources:
      WebsiteS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          LoggingConfiguration:
            DestinationBucketName:
              Ref: WebsiteS3LoggingBucket
      WebsiteS3LoggingBucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: LogDeliveryWrite
  expectations:
    rules:
      check_s3_bucket_is_logging: PASS
```

And I have the following rule:
```
let s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" ]

rule check_s3_bucket_is_logging when %s3_buckets !empty {
  %s3_buckets.Properties.AccessControl exists OR
  %s3_buckets.Properties.LoggingConfiguration exists
}
```

I would expect (based on https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/CLAUSES.md#named-rule-blocks - the "named rule blocks can be re-used and grouped together with other Guard rules" section) that the OR condition would work in this case. So, I would expect that my test passes, but it doesn't.

## Other Attempts
This results in a SKIP:
```
rule check_s3_bucket_is_logging when %s3_buckets !empty %s3_buckets.Properties.AccessControl != "LogDeliveryWrite" {
  %s3_buckets.Properties.LoggingConfiguration exists
}
```

This results in a FAIL:
```
rule check_s3_bucket_is_logging when %s3_buckets !empty {
  when s3_buckets.Properties.LoggingConfiguration exists {
    # Default pass
    s3_buckets.Properties.LoggingConfiguration exists
  }

  when s3_buckets.Properties.LoggingConfiguration !exists {
    %s3_buckets.Properties.AccessControl exists
  }
}
```

## Current Workaround
I have two queries and then check them separately:
```
let logging_s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" Properties.LoggingConfiguration exists]
let nonlogging_s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" Properties.LoggingConfiguration !exists]

rule check_most_s3_buckets_are_logging when %logging_s3_buckets !empty {
  # This doesn't really add value right now
  %logging_s3_buckets.Properties.LoggingConfiguration exists
}

rule check_nonlogging_s3_buckets_are_actually_logging_buckets when %nonlogging_s3_buckets !empty {
  %nonlogging_s3_buckets.Properties.AccessControl == "LogDeliveryWrite"
}
```

# My Ask
This feels a bit ugly. Am I doing something wrong?
