### ISSUE TITLE
[BUG] Documentation Update Needed

### ISSUE THREAD

**Issue by dchakrav-github** [aws-cloudformation/cloudformation-guard#136]
**Describe the bug**
Clauses documentation needs to be augmented to clarify how disjunction clauses work against query results. It specifically needs to clarify what are independent clauses vs conjoined clauses for evaluation. 

**To Reproduce**

Here is an example rule 
```
let s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" ]

rule check_s3_bucket_is_logging when %s3_buckets !empty {
  %s3_buckets.Properties.AccessControl exists OR
  %s3_buckets.Properties.LoggingConfiguration exists
}
```

Here is corresponding test file 
```YAML
- input:
    Resources:
      WebsiteS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          LoggingConfiguration:
            DestinationBucketName:
              Ref: WebsiteS3LoggingBucket
      WebsiteS3LoggingBucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: LogDeliveryWrite
  expectations:
    rules:
      check_s3_bucket_is_logging: PASS
```

Sample run
```bash
$ cfn-guard test -r s3-didnt-work.guard -t s3-tests.yaml 
FAILED Expected Rule = check_s3_bucket_is_logging, Status = PASS, Got Status = FAIL
```

**Expected behavior**
Expected PASS, got FAIL

**Operating System:**
[ALL]

**Additional context**
Documentation does not provide clarity on how the OR disjunction works for these clauses. Currently, the assumption being made by rule authors is for each S3 bucket present in the template the corresponding clauses are evaluated. However, for Guard's evaluation engine, these two separate independent clauses that are each individually assessed. 

**Independent Clauses**
```
   %s3_buckets.Properties.AccessControl exists OR
   %s3_buckets.Properties.LoggingConfiguration exists
```
Each clause is independently evaluated for all values of `%s3_buckets`. This above clauses are effectively stating either *ALL S3 Buckets* have AccessControl or *ALL S3 Buckets* have LoggingConfiguration specified.

**Conjoined Clauses**

```
let s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" ]
 
 rule check_s3_bucket_is_logging when %s3_buckets !empty {
     %s3_buckets {
         Properties.AccessControl exists OR
         Properties.LoggingConfiguration exists
     }
 }
```

Here all the clauses conjointly apply for all values of `%s3_bucket`. Here *ALL S3 Buckets* have either AccessControl or LoggingConfiguration specified.
