### ISSUE TITLE
duplicate rule names are allowed?

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-guard#162]
Are rules with the same name allowed?  This is considered valid according to the parser

```
rule check_a_value {
    a == 1
}

rule check_a_value {
    b == 1
}
```

When using OR rule logic the 2nd one will always win.
```
rule check_a_value {
    b == 1
}

rule check_a_value {
    b == 2
}

rule check_c_value {
    c == 3
}

rule check_a_or_c {
    check_a_value or check_c_value
}
```
with these tests
```
---
- input:
    a: 1
    b: 2
    c: 3
  expectations:
    rules:
      check_a_value: PASS
      check_c_value: PASS
      check_a_or_c: PASS
- input:
    a: 2
    b: 2
    c: 3
  expectations:
    rules:
      check_a_value: PASS
      check_c_value: PASS
      check_a_or_c: PASS
```
will result in 
```
PASS Expected Rule = check_a_value, Status = PASS, Got Status = PASS
PASS Expected Rule = check_a_value, Status = PASS, Got Status = PASS
PASS Expected Rule = check_c_value, Status = PASS, Got Status = PASS
PASS Expected Rule = check_a_or_c, Status = PASS, Got Status = PASS
FAILED Expected Rule = check_a_value, Status = PASS, Got Status = FAIL
PASS Expected Rule = check_a_value, Status = PASS, Got Status = PASS
PASS Expected Rule = check_c_value, Status = PASS, Got Status = PASS
PASS Expected Rule = check_a_or_c, Status = PASS, Got Status = PASS
```
