### ISSUE TITLE
[BUG] Validation fails on CFT with rules created in rulegen v2.0.2

### ISSUE THREAD

**Issue by Relativity11** [aws-cloudformation/cloudformation-guard#166]
**Describe the bug**
Validating some CloudFormation Templates against the rules created from them with rulegen fail ambiguously and do not give good debugging to describe why a failure occurred.

**To Reproduce**
Please supply:
1. Run a cfn-guard rulegen against a complex CFT.
2. Run a cfn-guard validate against the complex CFT and the generated rules.

Snippet Example:
`let aws_route53_recordset_resources = Resources.*[ Type == 'AWS::Route53::RecordSet' ]
rule aws_route53_recordset when %aws_route53_recordset_resources !empty {
  %aws_route53_recordset_resources.Properties.Type == "A"
  %aws_route53_recordset_resources.Properties.Name IN [["",["SubdomainMaster",".","HostedZoneName"]], ["",["SubdomainDefault",".","HostedZoneName"]], ["",["SubdomainInternal",".","HostedZoneName"]], ["",["SubdomainWild",".","HostedZoneName"]]]
  %aws_route53_recordset_resources.Properties.TTL == "900"
  %aws_route53_recordset_resources.Properties.Comment == "DNS name for my instance."
  %aws_route53_recordset_resources.Properties.HostedZoneName == "HostedZoneName"
  %aws_route53_recordset_resources.Properties.ResourceRecords IN [["Infra1.PrivateIp"], ["Master.PrivateIp"]]
}`

`  MasterRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneName'
      Comment: DNS name for my instance.
      Name: !Join ['', [!Ref 'SubdomainMaster', ., !Ref 'HostedZoneName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt Master.PrivateIp
  InternalRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneName'
      Comment: DNS name for my instance.
      Name: !Join ['', [!Ref 'SubdomainInternal', ., !Ref 'HostedZoneName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt Master.PrivateIp
  SubdomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneName'
      Comment: DNS name for my instance.
      Name: !Join ['', [!Ref 'SubdomainDefault', ., !Ref 'HostedZoneName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt Infra1.PrivateIp
  WildcardRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneName'
      Comment: DNS name for my instance.
      Name: !Join ['', [!Ref 'SubdomainWild', ., !Ref 'HostedZoneName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt Infra1.PrivateIp`

**Expected behavior**
All areas "PASS" when running rules against their own CFT.

**Screenshots**
![Screen Shot 2021-06-15 at 9 43 46 AM](https://user-images.githubusercontent.com/11866698/122065935-52b5e780-cdc0-11eb-925b-c78107370e7c.png)

**Operating System:**
MacOS 10.14
Fedora 34

**Additional context**
Some CFT fully PASS when running validation against their own rules, some do not.
Shouldn't validation ensure a full PASS when running CFT against the rules created in rulegen against themselves - always?

We have many templates and are unable to prep them individually for CFN-Guard.
Attempted multiple branches to see if failure persists.

Thank you for any input!

**Comment by dchakrav-github** [comment]
Thanks for report @Relativity11. Which version of 2.0 are you using? The latest release 2.0.2 had fixes that might address some of these value comparisons. Can you attach the sample CFN template here?

**Comment by dchakrav-github** [comment]
Recovered snippet as 

```yaml
Resources:
    MasterRecord: 
        Type: AWS::Route53::RecordSet 
        Properties: 
            HostedZoneName: !Ref 'HostedZoneName' 
            Comment: DNS name for my instance. 
            Name: !Join ['', [!Ref 'SubdomainMaster', ., !Ref 'HostedZoneName']] 
            Type: A 
            TTL: '900' 
            ResourceRecords: 
                - !GetAtt Master.PrivateIp 
    InternalRecord: 
        Type: AWS::Route53::RecordSet 
        Properties: 
            HostedZoneName: !Ref 'HostedZoneName' 
            Comment: DNS name for my instance. 
            Name: !Join ['', [!Ref 'SubdomainInternal', ., !Ref 'HostedZoneName']] 
            Type: A 
            TTL: '900' 
            ResourceRecords: 
                - !GetAtt Master.PrivateIp 
    SubdomainRecord: 
        Type: AWS::Route53::RecordSet 
        Properties: 
            HostedZoneName: !Ref 'HostedZoneName' 
            Comment: DNS name for my instance. 
            Name: !Join ['', [!Ref 'SubdomainDefault', ., !Ref 'HostedZoneName']] 
            Type: A 
            TTL: '900' 
            ResourceRecords: 
                - !GetAtt Infra1.PrivateIp 
    WildcardRecord: 
        Type: AWS::Route53::RecordSet 
        Properties: 
            HostedZoneName: !Ref 'HostedZoneName' 
            Comment: DNS name for my instance. 
            Name: !Join ['', [!Ref 'SubdomainWild', ., !Ref 'HostedZoneName']] 
            Type: A 
            TTL: '900' 
            ResourceRecords: 
                - !GetAtt Infra1.PrivateIp
```

Reproduced bug reported with above template. Fix issue and tested it locally. Update being pushed as a part of PR #159
