### ISSUE TITLE
Help creating required tags rule

### ISSUE THREAD

**Issue by kidbrax** [aws-cloudformation/cloudformation-guard#176]
How would I go about enforcing that certain resources have a set of required Tag Keys using v2. I have tried something like this:

```
let required_tag_types = [
  /AWS::EC2::Instance/,
  /AWS::S3::Bucket/
]
let required_tag_resources = Resources.*[
  Type in %required_tag_types
]

rule required_tags when %required_tag_resources !empty {
  %resources.Properties.Tags[0].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[1].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[2].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[3].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[4].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[5].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
  %resources.Properties.Tags[6].Key IN ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
}
```

This should ensure that all instances and buckets have at least 6 tags and those first 6 tags' keys appear in that list. But this only works in some files and not in others. 

I sometimes receive this error: `Error occurred Variable assignment could not be resolved in rule file or incoming context Could not resolve variable resources`. Dos that mean there are no instances/buckets or that they exist but don't have tags?

And lastly, this would mean the required keys have to be in the first 6 tags which isn't a deal-breaker but would prefer to look across any order. Essentially, I want to say the tag keys for this resource include the array given.

**Comment by dchakrav-github** [comment]
@kidbrax it would be useful if you attached a sample template, unit tests performed to the issue. Couple of observations

1. `%resources` isn't defined, hence the error, it should refer to `%required_tag_resources` that is defined.
2. You want to ensure that the following `["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]` keys are mandatory and MUST be present in all `Tags` for S3/EC2.  There CAN be more `Tags` present. See rule definition below
3. We do not have a `count` function, we will add this to the backlog to add

Rule 

```
let required_tag_types = [
  /AWS::EC2::Instance/,
  /AWS::S3::Bucket/
]
let required_tag_resources = Resources.*[
  Type in %required_tag_types
]

let mandatory_keys = ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
rule required_tags when %required_tag_resources !empty {
  %required_tag_resources { # for each resource
    let all_tag_keys_for_resource = Properties.Tags[*].Key
    %mandatory_keys IN %all_tag_keys_for_resource # ensure that all mandated keys are indeed present for the resource
  } 
}
```

Sample Testing
```
---
- name: test mandatory keys pass
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: PASS
- name: test mandatory keys fail, missing Name
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: FAIL
- name: test mandatory keys fail, missing Name in s3 resource
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
      s3Pass:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: FAIL
- name: test mandatory keys pass mixed types
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
      ec2:
        Type: AWS::EC2::Instance
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: PASS

```
