### ISSUE TITLE
Help wanted with cfn-guard rule to check properties in two resources.

### ISSUE THREAD

**Issue by TheFlexican** [aws-cloudformation/cloudformation-guard#184]
Looking for some help with the below show example. Is it possible to create a cfn-guard rule for the below example? I was unable to find in the documentation. 

Ensure that 'AcceptanceRequired' is set to 'true' whenever a wildcard ('*') is used within the permission for the same resource. So basically 'following' the !Ref in the to VPCEndpointServicePermissions to the VPCEndpointService to find the property AcceptanceRequired and compare it to value I want.

MyEndpointService:
  Type: AWS::EC2::VPCEndpointService
  Properties:
    AcceptanceRequired: true
 
MyEndpointServicePermissions:
  Type: AWS::EC2::VPCEndpointServicePermissions
  Properties:
    AllowedPrincipals:
      - '*'
    ServiceId: !Ref MyEndpointService

Any help is appreciated!

**Comment by priyap286** [comment]
@TheFlexican 

You can do something like this,

Example YAML template:
```yaml
Resources:
  MyEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      AcceptanceRequired: true

  MyEndpointServicePermissions:
    Type: AWS::EC2::VPCEndpointServicePermissions
    Properties:
      AllowedPrincipals:
        - "*"
      ServiceId:
        Ref: MyEndpointService
```

Example Rules:
```
let permissions = Resources.*[ 
    Type == /Permissions/
    Properties.AllowedPrincipals == '*'
]

let resource = %permissions.Properties.ServiceId.Ref

Resources.%resource.Properties.AcceptanceRequired == true
```
Please let me know if this resolves your issue so that I can close the issue.

**Comment by dchakrav-github** [comment]
Yes, this is supported. Here is the rule 

```
let vpc_endpoint_permisssions = Resources.*[
    # 
    # Select all Permissions resource types
    # 
    Type == 'AWS::EC2::VPCEndpointServicePermissions'

    #
    # And only select those that have 
    # 
    Properties {
      #
      # atleast one AllowedPrincipal that is a wild card
      #
      some AllowedPrincipals[*] == '*'

      #
      # And has a local reference to VPCEndpointService
      #
      ServiceId.Ref exists
    }
]

rule ensure_vpc_endpoint_service_accepted when %vpc_endpoint_permisssions not empty {
    # Get all the values of the Ref
    let vpc_endpoint_refs = %vpc_endpoint_permisssions.Properties.ServiceId.Ref

    #
    # Lookup the reference by name
    # 
    let vpc_endpoints = Resources.%vpc_endpoint_refs

    #
    # For each of these
    #
    %vpc_endpoints {
        # 
        # Ensure that it is an VPCEndpointService type
        # 
        Type == 'AWS::EC2::VPCEndpointService'

        #
        # Ensure AcceptanceRequired is set to true
        # 
        Properties.AcceptanceRequired == true
    }
}
```

And the test file 

```
---
- name: PASS for example shown
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: PASS

- name: Acceptance Required was set to false
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: false
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: FAIL

- name: Missing Acceptance required leads to FAIL
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: FAIL

- name: Missing attribute, but still skip as Allowed principals did not contain '*'
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - ec2.amazonaws.com # SKIP
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: SKIP

- name: Skipped as Allowed Principals does not contain '*'
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true # still SKIP as allowed principal does not have '*'
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - ec2.amazonaws.com # SKIP
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: SKIP

- name: Fail as '*' is contained in addition to non '*' ones
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals:
            - ec2.amazonaws.com 
            - '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: FAIL

- name: Checks correctly when Allowed Principals takes non-array single value form
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: PASS

- name: check out for 2 occurences
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: 
            Ref: vpce
      vpce2: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms2:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: 
            Ref: vpce
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: PASS

- name: check out for 2 occurences
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: 
            Ref: vpce
      vpce2: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: false
      vpcePerms2:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: 
            Ref: vpce2
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: FAIL

- name: SKIP when there is no local reference to VPC ID
  input:
    Resources:
      vpce: 
        Type: AWS::EC2::VPCEndpointService
        Properties:
          AcceptanceRequired: true 
      vpcePerms:
        Type: AWS::EC2::VPCEndpointServicePermissions
        Properties:
          AllowedPrincipals: '*'
          ServiceId: aws:arn:...
  expectations:
    rules:
      ensure_vpc_endpoint_service_accepted: SKIP

```
