### ISSUE TITLE
Filter based on Resource Logical ID

### ISSUE THREAD

**Issue by longtv2222** [aws-cloudformation/cloudformation-guard#186]
I want to be able to write query that exclude resources with certain LogicalID

Let's say we have a cf template that looks like this.

```json
{
  "Resources": {
    "NewVolume": {
      "Type": "AWS::EC2::Volume",
      "Properties": {
        "Size": 123,
        "Encrypted": true,
        "AvailabilityZone": "us-west-2b"
      }
    },
    "NewVolume2": {
      "Type": "AWS::EC2::Volume",
      "Properties": {
        "Size": 100,
        "Encrypted": true,
        "AvailabilityZone": "us-west-2c"
      }
    }
  }
}
```
We can query resources of all resources of type AWS::EC2::Volume by
 ```let aws_ec2_volume_resources = Resources.*[ Type == 'AWS::EC2::Volume' ]```

But I want to query resources of type AWS::EC2::Volume with LogicalID that is **not** NewVolume2. Ideally, I should be able to make a list of value of excluded LogicalID

Is this feature supported or is there a workaround as I don't see it documented anywhere.

**Comment by dchakrav-github** [comment]
There are 2 aspects to this
1. There is a bug, the parser was updated to accept `!=, IN, !IN` comparison operators, but then evaluator was not updated along with it. We will issue a fix for this.
2. You want to select resources by both `Type` attribute and the logical name match. They are present in different parts of the incoming payload traversal hierarchy. Today, once you traverse down, you can select attributes to check at that level and children. Here you are traversing up one level to check for logical IDs. We don't support this today. We have a backlog feature for capturing the key for a struct or index for an array into a variable and using that. E.g. you would be able to model it using 
```
let matches = [ /Volume$/, /VolumePat2$/ ]
let  candidate_ec2_volumes = Resources[ ec2_vol_name | Type == 'AWS::EC2::Volume' ]
let select_only_matched = %ec2_vol_name[ this IN %matches ].*
let volumes = Resources.%selected_only_match
```

**Comment by longtv2222** [comment]
Thank you @dchakrav-github, this is excellent tool so far and I really enjoy working with cfn-guard. I'm writing compliance policy, I want to have an option to opt out certain rules but since I couldn't exclude resources logical ID directly on cfn-guard, I managed to overcome this issue by using CloudFormation metadata

``` 
let s3_bucket_resource = Resources.*[ Type == 'AWS::S3::Bucket' ]
let no_metadata_resources = %s3_bucket_resource[Metadata.guardRailExclude not exists]

# Rule ID: S3_Bucket_#1
# Rule Intent: S3 Bucket versioning must be enabled

rule s3_bucket_versioning_enabled when %no_metadata_resources not empty OR %s3_bucket_resource[ Metadata.guardRailExclude[*].id != 'S3_Bucket_#1'] !empty {
    %s3_bucket_resource {
        Properties.VersioningConfiguration.Status == 'Enabled'
    }
}
```

And the test file:

```yaml
- input:
    "Resources":
      {
        "TestBucket":
          {
            "Type": "AWS::S3::Bucket",
            "Metadata":
              {
                "guardRailExclude":
                  [
                    {
                      "id": "S3_Bucket_#1",
                      "reason": "Test to see if we bucket is skipped given S3_Bucket_#1 metadata id",
                    },
                  ],
              },
          },
      }
  expectations:
    rules:
      s3_bucket_versioning_enabled: SKIP
```
