### ISSUE TITLE
[GENERAL ISSUE] General Guidance for if equivalent needed

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws-cloudformation/cloudformation-guard#205]
What is the  best way to do this?

I'm going through webacl's, some rules will be rate based others will not be.

I need to check if Limit is > 500, but only on the rules which are rate based (ie. if Statement.RateBasedStatement.Limit exists.)

What's a better/different way to do that?  Below is what I currently have, which works.

`let aws_wafv2_webacl_resources = Resources.*[ Type == 'AWS::WAFv2::WebACL' ]
rule aws_wafv2_webacl when %aws_wafv2_webacl_resources !empty {
  %aws_wafv2_webacl_resources.Properties.Rules[*].Statement.RateBasedStatement.Limit !EXISTS OR %aws_wafv2_webacl_resources.Properties.Rules[*].Statement.RateBasedStatement.Limit>500
}`

**Comment by dchakrav-github** [comment]
Select all rules that are `RateBasedStatement` and check only for those. Here is the rule 

```
rule aws_wafv2_webacl when %aws_wafv2_webacl_resources !empty {
      let rate_limited = some %aws_wafv2_webacl_resources.Properties.Rules[*].Statement.RateBasedStatement
      when %rate_limited not empty {
               %rate_limited > 500
      }
}
```

Sample tests

```yaml
---
- name: empty SKIP
  input:
    Resources: {}
  expectations:
    rules:
      aws_wafv2_webacl: SKIP

- name: Single WebACL, PASS
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
  expectations:
    rules:
      aws_wafv2_webacl: PASS

- name: Multiple WebACL, PASS
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
  expectations:
    rules:
      aws_wafv2_webacl: PASS

- name: Multiple WebACL, FAIL
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 500 # FAIL not > 500
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
  expectations:
    rules:
      aws_wafv2_webacl: FAIL
```

sample test run

```
~/.guard/bin/cfn-guard test -r rule.guard -t tests/rule_tests.yaml
Test Case #1
Name: "empty SKIP"
  PASS Rules:
    aws_wafv2_webacl: Expected = SKIP, Evaluated = SKIP

Test Case #2
Name: "Single WebACL, PASS"
  PASS Rules:
    aws_wafv2_webacl: Expected = PASS, Evaluated = PASS

Test Case #3
Name: "Multiple WebACL, PASS"
  PASS Rules:
    aws_wafv2_webacl: Expected = PASS, Evaluated = PASS

Test Case #4
Name: "Multiple WebACL, FAIL"
  PASS Rules:
    aws_wafv2_webacl: Expected = FAIL, Evaluated = FAIL

```

The statement `let rate_limited = some %aws_wafv2_webacl_resources.Properties.Rules[*].Statement.RateBasedStatement` is just a short form for filter expression below

```
%aws_wafv2_webacl_resources.Properties.Rules[ Statement.RateBasedStatement exists ].Statement.RateBasedStatemen
```
It picks all `Rules` elements that have `Statement.RateBaseStatement` in them

**Comment by dchakrav-github** [comment]
With the upcoming release, rule can recursively check. In the case of WAFv2 Rules, `AndStatement` and `OrStatement` can refer to `RateBasedStatement`. The same rule with the latest release is as shown below 

```
let aws_wafv2_webacl_resources = Resources[ Type == 'AWS::WAFv2::WebACL' ]
rule deny_aws_wafv2_webacl_incorrect_rate_limits {
    check_rate_limit_statement(%aws_wafv2_webacl_resources.Properties.Rules[*].Statement)
}

#
# Named rules
#
rule check_rate_limit_statement(statements) {
    %statements[ RateBasedStatement exists ] {
        RateBasedStatement.Limit > 500
    }

    %statements[ AndStatement exists ] {
        check_rate_limit_statement(AndStatement.Statements[*])
    }

    %statements[ OrStatement exists ] {
        check_rate_limit_statement(OrStatement.Statements[*])
    }
}
```
Sample tests

```
---
- name: empty SKIP
  input:
    Resources: {}
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: SKIP

- name: Single WebACL, PASS
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: PASS

- name: Multiple WebACL, PASS
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: PASS

- name: Multiple WebACL, FAIL
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 500 # FAIL not > 500
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: FAIL

- name: Multiple WebACL, PASS
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                AndStatement:
                  Statements:
                    - OrStatement:
                        Statements:
                        - RateBasedStatement:
                              Limit: 600
                        - IPSetReferenceStatement:
                              Arn: arn:aws:...                  
                    - RateBasedStatement:
                          Limit: 600
                    - IPSetReferenceStatement:
                          Arn: arn:aws:...                  
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: PASS

- name: Multiple WebACL, FAIL
  input:
    Resources: 
      webAcl:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                RateBasedStatement:
                  Limit: 600
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                IPSetReferenceStatement:
                  Arn: arn:aws:...                  
      webAcl2:
        Type: 'AWS::WAFv2::WebACL'
        Properties:
          Rules:
            - Statement:
                AndStatement:
                  Statements:
                    - OrStatement:
                        Statements:
                        - RateBasedStatement:
                              Limit: 400 # FAIL <= 500
                        - IPSetReferenceStatement:
                              Arn: arn:aws:...                  
                    - RateBasedStatement:
                          Limit: 600
                    - IPSetReferenceStatement:
                          Arn: arn:aws:...                  
  expectations:
    rules:
      deny_aws_wafv2_webacl_incorrect_rate_limits: FAIL

```

Sample run
