### ISSUE TITLE
cfn-guard-lambda: document how to pass YAML templates and multi-line Guard rules

### ISSUE THREAD

**Issue by mrinaudo-aws** [aws-cloudformation/cloudformation-guard#209]
**Describe the issue**
Document how to pass YAML templates and multi-line Guard rules as inputs to `cfn-guard-lambda`.  For example, given a sample YAML template such as:

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample template
Resources:
  SampleVolume:
    Type: AWS::EC2::Volume
    Properties:
      Encrypted: true
      Size: 10
```

and a sample Guard rule:

```
AWS::EC2::Volume {
    Properties {
        Encrypted == true
        Size <= 10
    }
}
```

document and provide an example of the expected format to use to pass information (as in above examples) as part of the [payload structure](https://github.com/aws-cloudformation/cloudformation-guard/tree/main/guard-lambda#calling-the-aws-lambda-function).

**Any examples**
-

**Operating System:**
-

**OS Version**
-

**Additional context**
-
