### ISSUE TITLE
[GENERAL ISSUE] Is there a way to do some sort of exception handling ?

### ISSUE THREAD

**Issue by TheFlexican** [aws-cloudformation/cloudformation-guard#223]
**Describe the issue**
For example, resource X can't be made compliant to our AWS config rules by team Y for reason Z. We created exception handling after deployment for team Y, and are now only focusing on the before deployment part. 
We still want to have the cfn-guard rule that matches the AWS config rule mentioned above, so we block deployment for other teams. We want to implement exception handling for team Y in the CI pipeline were cfn-guard is running. The thing we thought of now, would be team Y needs to add a tag to the resource they want an exception for, with the key name of the config rule, and value exception.  
A cfn-guard example rule I thought of that would match this would look something like example below. This would first check if AccessControl is not PublicReadWrite, if it is, it would then evaluate the Tags property and look for Key == "aws-config-rule-1"  and Value == "exception". This works as far as I have tested it, with playing around with the tags and the value of AccessControl .

The issue I'm facing is, it would report all the keys,values in Tags that are part of this resource as non compliant, when the resource is NOT tagged with the key aws config rule and a value of exception because they do not match the expected key and value provided below. Is there a way to suppress the non compliant messages on the tags, or is there maybe better way to handle exceptions? Cause I got to admit, this doesn't look nice. 

cfn-guard rule
```
let aws_s3_buckets = Resources.*[ Type == "AWS::S3::Bucket" ]

rule aws_s3_bucket_accesscontrol WHEN %aws_s3_buckets NOT EMPTY {
    %aws_s3_buckets {
        when Properties.AccessControl exists {
            Properties.AccessControl != /(?i)(PublicReadWrite)/ <<Do not do this>>
        OR 
            some Properties.Tags[*] {
                Key == "aws-config-rule-1" 
                Value == "exception" 
            }
        }
    }
}
```

output of this rule validated against a template
```
cfn-guard validate -d sam.yaml -r ./rules/s3/access/s3-bucket-access.guard  --output-format yaml  
sam.yaml Status = FAIL
FAILED rules
s3-bucket-access.guard/aws_s3_bucket_accesscontrol    FAIL
---
---
data_from: sam.yaml
rules_from: s3-bucket-access.guard
not_compliant:
  aws_s3_bucket_accesscontrol:
    - rule: aws_s3_bucket_accesscontrol
      path: /Resources/S3Bucket/Properties/AccessControl
      provided: PublicReadWrite
      expected: /(?i)(PublicReadWrite)/
      comparison:
        operator: Eq
        not_operator_exists: true
      message: Do not do this
    - rule: aws_s3_bucket_accesscontrol
      path: /Resources/S3Bucket/Properties/Tags/0/Key
      provided: test
      expected: aws-config-rule-1
      comparison:
        operator: Eq
        not_operator_exists: false
      message: ""
    - rule: aws_s3_bucket_accesscontrol
      path: /Resources/S3Bucket/Properties/Tags/0/Value
      provided: test
      expected: exception
      comparison:
        operator: Eq
        not_operator_exists: false
      message: ""
not_applicable: []
compliant: []
```

template
```
Transform: AWS::Serverless-2016-10-31
Description: "test"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicReadWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: test
          Value: test
        # - Key: aws-config-rule-1
        #   Value: exception
```
