### ISSUE TITLE
[BUG] `empty` Function Broken on Boolean Keys

### ISSUE THREAD

**Issue by SamPlatek** [aws-cloudformation/cloudformation-guard#266]
**Describe the bug**
The `empty` function throws the following error when targeting a Boolean key, which did not happen in previous versions of CFN Guard.

`Error occurred Types or variable assignments are incompatible Attempting EMPTY operation on type bool that does not support it at /Resources/MyAPIGateway/Properties/MethodSettings/0/MetricsEnabled`

**To Reproduce**
Please supply:

1. Example rules and template that results in the error
**Rule Definition**:
```
%api_gateways {
  Properties.MethodSettings[*] {
    MetricsEnabled !empty
    DataTraceEnabled !empty
  }
}
```

Sample test data that produced the failure:

```
- input:
    Resources:
      MyAPIGateway:
        Type: AWS::Serverless::Api
        Properties:
          StageName: prod
          MethodSettings:
            - ResourcePath: /
              HttpMethod: GET
              MetricsEnabled: false
              DataTraceEnabled: false
              LoggingLevel: false
```

1. The commands you used to invoke the tool
Breaks both when `validate` and `test` are used - with the same error messages

1. The output of a `-v` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the cfn-guard-lambda

**NOTE: Please be sure that the templates, rules and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**

`empty` should be able to interrogate any key, irregardless of the type. It is expected to be used in place of `exists` to check whether a key actually exists (per the docs and multiple tickets I've read here) and therefore is vital to governance for many resources which have default boolean options.

**Operating System:**
MacOS

**OS Version**
Monterey

**Additional context**
