### ISSUE TITLE
[GENERAL ISSUE] Question: how to filter by logical ID

### ISSUE THREAD

**Issue by polothy** [aws-cloudformation/cloudformation-guard#267]
**Describe the issue**

Attempting to author a rule that verifies that a `AWS::EC2::FlowLog` has been created for every `AWS::EC2::VPC`.  See the below example, but the problem is likely in the rule where I have `let flow_log` defined.  I'm trying to lookup the FlowLog by the logical ID of the VPC.  I have seen examples of these logical ID lookups, but in the reverse order (EG: loop through FlowLogs and find VPCs).

**Any examples**

Guard rule:

```
#
# Select all VPCs
#
let vpcs = Resources.*[ Type == 'AWS::EC2::VPC' 
  Metadata.guard.SuppressedRules not exists or 
  Metadata.guard.SuppressedRules.* != "VPC_FLOW_LOGS_ENABLED"
]

rule VPC_FLOW_LOGS_ENABLED when %vpcs !empty {
  let flow_log = Resources.*[ Type == 'AWS::EC2::FlowLog'
    some Properties.ResourceId.Ref == %vpcs
  ]
  %flow_log !empty
  <<
  	Violation: VPC must have flow logs enabled
  	Fix: create a AWS::EC2::FlowLog for the VPC
  >>
}
```

Tests:

```yaml
###
# VPC_FLOW_LOGS_ENABLED tests
###
---
- name: Empty, SKIP
  input: {}
  expectations:
    rules:
      VPC_FLOW_LOGS_ENABLED: SKIP

- name: No resources, SKIP
  input:
    Resources: {}
  expectations:
    rules:
      VPC_FLOW_LOGS_ENABLED: SKIP

- name: VPC and Flow Logs resource, PASS
  input:
    Resources:
      Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: 10.0.0.0/16
          EnableDnsHostnames: true
          EnableDnsSupport: true
          InstanceTenancy: default
      FlowLog:
        Type: AWS::EC2::FlowLog
        Properties:
          ResourceId:
            Ref: Vpc
          ResourceType: VPC
          TrafficType: ALL
          DeliverLogsPermissionArn:
            Fn::GetAtt:
              - IamRole
              - Arn
          LogDestinationType: cloud-watch-logs
          LogGroupName:
            Ref: LogGroup
  expectations:
    rules:
      VPC_FLOW_LOGS_ENABLED: PASS

- name: VPC with Flow Logs resource missing, FAIL
  input:
    Resources:
      Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: 10.0.0.0/16
          EnableDnsHostnames: true
          EnableDnsSupport: true
          InstanceTenancy: default
  expectations:
    rules:
      VPC_FLOW_LOGS_ENABLED: FAIL
```

**Operating System:**
MacOS

**OS Version**
Monterey

**Additional context**
None.

**Comment by polothy** [comment]
Hey @akshayrane - just noticed that you assigned this to yourself. Is there a quick response to this question? Just a "yes, there is a way" or "no, this requires (big/small) changes to Guard"?  Been evaluating Guard and [cdk-nag](https://github.com/cdklabs/cdk-nag) for compliance enforcement/checking and I ran into this issue.

**Comment by akshayrane** [comment]
Hi @polothy 

Thanks for reaching out. Short answer is yes, there is a way to extract a resource using its logical name and add checks on it. However, we are evaluating at the moment how can it be extended to meet your exact use case.

Here's a sample rule to extract a resource with known pattern and add check for a specific property, `rule.guard`:
```
let flow_logs = Resources[ keys == /FlowLog/ ]
rule ensure_logs_have_some_props when %flow_logs !empty {
    %flow_logs.Properties{
        TrafficType == 'ALL'
        <<
            Violation: TrafficType should be ALL
        >>
    }
}
```
 Corresponding data template, `template.yml`
```
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId:
        Ref: Vpc
      ResourceType: VPC
      TrafficType: ALL
      DeliverLogsPermissionArn:
        Fn::GetAtt:
          - IamRole
          - Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName:
        Ref: LogGroup
```

### Command
```
cfn-guard validate \
	-d template.yml \
	-r rule.guard \
 	--show-summary all
```
### Output
```
template.yml Status = PASS
PASS rules
rule.guard/ensure_logs_have_some_props    PASS
```

If you see a way you can re-use this functionality and solve your problem do let us know how your final rule looks like. 

HTH,
Akshay

**Comment by polothy** [comment]
Hey @akshayrane - thanks for commenting back, very much appreciated 😄 

Hrm, I'm not sure how this would help. I cannot make any assumptions about the logical ID because we have a wide range of CFN templates and we also use CDK (logical IDs can be pretty wild).  In addition, I'd like to make sure that the VPC and the flow log are connected (the logical ID of the VPC is in the definition of the flow log).

The rule I'm trying to write would cover this control: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-2.9

I think the problem I'm having would also be experienced when trying to write [this rule](https://github.com/aws-cloudformation/aws-guard-rules-registry/issues/86). It's a common pattern in CFN where you define a resource and then "attach it" to another resource.  So, solving this sort of tracing/linking problem would help with a lot of use cases as you build out the rules registry.

Cheers and thanks for your continued help on this!

**Comment by polothy** [comment]
Hey @akshayrane - thanks for commenting back, very much appreciated 😄 

Hrm, I'm not sure how this would help. I cannot make any assumptions about the logical ID because we have a wide range of CFN templates and we also use CDK (logical IDs can be pretty wild).  In addition, I'd like to make sure that the VPC and the flow log are connected (the logical ID of the VPC is in the definition of the flow log).

The rule I'm trying to write would cover this control: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-2.9

I think the problem I'm having would also be experienced when trying to write [this rule](https://github.com/aws-cloudformation/aws-guard-rules-registry/issues/86). It's a common pattern in CFN where you define a resource and then "attach it" to another resource.  So, solving this sort of tracing/linking problem would help with a lot of use cases as you build out the rules registry.

Cheers and thanks for your continued help on this!

**Comment by polothy** [comment]
Found another example that I think would be resolvable if this issue was fixed: https://github.com/aws-cloudformation/aws-guard-rules-registry/issues/240

**Comment by polothy** [comment]
@akshayrane hello, with v3 released, would this issue be addressed soon'ish?

**Comment by akshayrane** [comment]
Hi @polothy 

This should be possible to do, referring to a logical ID from a different resource and checking properties for this linked resource. But we would need to address the possibility of reference NOT being used elsewhere (which isn't handled in the following example).

The rule would look like:

```
let flow_logs = Resources.*[ Type == 'AWS::EC2::FlowLog' ]

rule ensure_logs_have_some_props when %flow_logs !empty {
    let vpc_logical_id = %flow_logs.Properties.ResourceId.Ref

    when %vpc_logical_id exists {
        let vpc = Resources[ keys == %vpc_logical_id ]

        %vpc.Properties.EnableDnsHostnames == true
        <<
            Violation: EnableDnsHostnames should be false
        >>
    }

}
```

The template is:
```yaml
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId:
        Ref: Vpc
      ResourceType: VPC
      TrafficType: ALL
      DeliverLogsPermissionArn:
        Fn::GetAtt:
          - IamRole
          - Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName:
        Ref: LogGroup
  FlowLog2:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId:
        !Ref Vpc
      ResourceType: VPC
      TrafficType: ALL
      DeliverLogsPermissionArn:
        Fn::GetAtt:
          - IamRole
          - Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName:
        Ref: LogGroup
```
Output:
```bash
$ cfn-guard validate -d data/issue-267.yml -r rules/issue-267.guard -S all
issue-267.yml Status = PASS
PASS rules
issue-267.guard/ensure_logs_have_some_props    PASS
---
```

Please us know if it's okay to mark the issue as resolved.

HTH,
Akshay

**Comment by polothy** [comment]
Hey @akshayrane - thank you so much for the followup!

The security control that we are enforcing says that all VPCs must have flow logs. The above example would pass if I just had a VPC defined but no flow logs defined. We use the same Guard file across all our microservices.  Most microservices do not have a VPC defined, so we cannot assume there is always at least one VPC in the template.

Same exact scenario with the security control where S3 bucket must only accept SSL connections.  For each S3 bucket, we must look up the bucket policy resource and see if there is a statement enforcing SSL.

This pattern repeats a lot throughout CloudFormation.

**Comment by joshfried-aws** [comment]
Hi @polothy does this better handle your use case? I built upon what my colleague @akshayrane  had posted before. 

This handles all the test cases in your provided example. If vpcs are present, flow logs must be present as well. It also ensures that every referenced VPC logical id for each flow log is unique meaning 2 flow logs cannot reference the same VPC (not sure if this was a requirement i have left a comment in the rule to help you remove it if need be). This also means that the number of Flow Log resource types == the number of VPC resource types. We are able to do this by querying for all the ref'd VPCs and then ensuring that they're only present one time in our query (using the new builtin count function). We then loop over each defined Flow Log resource and ensure that the we're able to map the referenced logical id, we then validate the property as shown below. 

**Please note since this does use the new `count` function this will only work on cfn-guard v3.x.x and above**

```
let vpcs = Resources.*[ Type == "AWS::EC2::VPC" ]

rule VPC_FLOW_LOGS_ENABLED when %vpcs !empty {
    let flow_logs = Resources.*[ Type == 'AWS::EC2::FlowLog' ]
    %flow_logs !empty
    
    let res = Resources # have to do this because of the loop below, will lose the 'root context'

    %flow_logs.Properties.ResourceId.Ref exists

    let refs = %flow_logs.Properties.ResourceId.refs

    # this also makes sure that all refs are unique logical ids, can omit if this is not a necessary requirement
    %refs {
        let curr_ref = this 
        let check = %refs[ this == %curr_ref ] 

        let num = count(%check)

        %num == 1
    }

    %flow_logs {
        let vpc_logical_id = this.Properties.ResourceId.Ref
        %vpc_logical_id exists

        let vpc = %res[ keys == %vpc_logical_id ]
        
        %vpc.Properties.EnableDnsHostnames == true
        <<
            Violation: EnableDnsHostnames should be false
        >>
    }
}
```

Please let me know if this answer was sufficient. 

Thanks,

**Comment by polothy** [comment]
Hey Josh, thanks for the reply. It does not appear to attempt to create a 1 to 1 relationship.  For example, this does not pass:

```yaml
- name: Two VPCc and only one Flow Logs resource, FAIL
  input:
    Resources:
      Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: 10.0.0.0/16
          EnableDnsHostnames: true
          EnableDnsSupport: true
          InstanceTenancy: default
      Vpc2:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: 10.0.0.0/16
          EnableDnsHostnames: true
          EnableDnsSupport: true
          InstanceTenancy: default
      FlowLog:
        Type: AWS::EC2::FlowLog
        Properties:
          ResourceId:
            Ref: Vpc2
          ResourceType: VPC
          TrafficType: ALL
          DeliverLogsPermissionArn:
            Fn::GetAtt:
              - IamRole
              - Arn
          LogDestinationType: cloud-watch-logs
          LogGroupName:
            Ref: LogGroup
  expectations:
    rules:
      VPC_FLOW_LOGS_ENABLED: FAIL
```

2 VPCs, but only 1 flow logs.

Just a general feedback type of thing, this pattern repeats throughout CloudFormation a lot. So, while a workaround is nice, a concise way to express/enforce this pattern would be very helpful because this will be repeated a lot across many rules.

Cheers and thanks!
