### ISSUE TITLE
[BUG] How to add required tags for AWS Resources

### ISSUE THREAD

**Issue by alfonso-clip** [aws-cloudformation/cloudformation-guard#273]
_Originally posted by @alfonso-clip in https://github.com/aws-cloudformation/cloudformation-guard/issues/176#issuecomment-1248828700_

I want to add required tags for many AWS Resources (but I'm trying with S3 first), but when using the same rule and the same yaml file, I can't get the same output in the test.
I'm using version 2.1.0 an this is the output that I get:

```
Test Case #1
Name: "test mandatory keys pass"
  PASS Rules:
    required_tags: Expected = PASS

Test Case #2
Name: "test mandatory keys pass, order does not matter"
  PASS Rules:
    required_tags: Expected = PASS

Test Case #3
Name: "test mandatory keys pass"
  PASS Rules:
    required_tags: Expected = PASS

Test Case #4
Name: "test mandatory keys fail, missing Name"
  FAIL Rules:
    required_tags: Expected = FAIL, Evaluated = [PASS]

Test Case #5
Name: "test mandatory keys fail, missing Name in s3 resource"
  FAIL Rules:
    required_tags: Expected = FAIL, Evaluated = [PASS]

Test Case #6
Name: "test mandatory keys pass mixed types"
  PASS Rules:
    required_tags: Expected = PASS
```
    
So when it should FAIL it PASS for me and I can't set the mandatory tags for my rule it always PASS

This is the rule that I used:

```
let required_tag_types = [
  /AWS::EC2::Instance/,
  /AWS::S3::Bucket/
]
let required_tag_resources = Resources.*[
  Type in %required_tag_types
]

let mandatory_keys = ["Name", "component", "creator", "env", "lifecycle", "owner_team", "project"]
rule required_tags when %required_tag_resources !empty {
  %required_tag_resources { # for each resource
    let all_tag_keys_for_resource = Properties.Tags[*].Key
    %mandatory_keys IN %all_tag_keys_for_resource # ensure that all mandated keys are indeed present for the resource
  } 
}

```

And finally the yml file with the test:

```

---
- name: test mandatory keys pass
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: PASS

- name: test mandatory keys pass, order does not matter
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: creator
              Value: Name
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: env
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
            - Key: lifecycle
              Value: Name
  expectations:
    rules:
      required_tags: PASS

- name: test mandatory keys pass
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: PASS

- name: test mandatory keys fail, missing Name
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: FAIL

- name: test mandatory keys fail, missing Name in s3 resource
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
      s3Pass:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: FAIL

- name: test mandatory keys pass mixed types
  input: 
    Resources:
      s3:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
      ec2:
        Type: AWS::EC2::Instance
        Properties:
          Tags:
            - Key: Name
              Value: Name
            - Key: component
              Value: Name
            - Key: creator
              Value: Name
            - Key: env
              Value: Name
            - Key: lifecycle
              Value: Name
            - Key: owner_team
              Value: Name
            - Key: project
              Value: Name
            - Key: some_other_key
              Value: Name
  expectations:
    rules:
      required_tags: PASS

```
