### ISSUE TITLE
Detecting ports within security groups

### ISSUE THREAD

**Issue by 0x10F8** [aws-cloudformation/cloudformation-guard#277]
Using the example provided here: https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/CONTEXTAWARE_EVALUATIONS_AND_LOOPS.md

I had hoped to detect dangerous open ports through cfg, although rather than defining the blocked ports within the cloudformation script, I'd rather they were within the guard itself. 

I came up with the following:
```
let sg_resources = Resources.*[
	Type == "AWS::EC2::SecurityGroup"
]

let dangerous_ports = [20, 21, 22, 23, 25, 53, 80, 88, 123, 389, 445, 5432]

# FTP           20, 21
# SSH           22
# Telnet        23
# SMTP          25
# DNS           53
# HTTP          80
# Kerberos      88
# NTP           123
# LDAP          389
# SMB           445
# PostgreSQL    5432



let sg_resources = Resources.*[
	Type == "AWS::EC2::SecurityGroup"
]

rule security_group_dangerous_ports when %sg_resources !empty {
    %sg_resources {
        Properties {
            SecurityGroupIngress !exists OR
            SecurityGroupIngress exists
            when SecurityGroupIngress exists {
                SecurityGroupIngress.* {
                    when IpProtocol in ['tcp', 'udp'] {
                        when CidrIp == '0.0.0.0/0' or
                                CidrIpv6 == '::/0' {
                            let each_ingress = this
                            %dangerous_ports {
                                this < %each_ingress.FromPort or
                                this > %each_ingress.ToPort
                            }
                        }
                    }
                }
            }
        }
	}
}
```

With a basic test:
```
- name: "Test inbound safe ports succeed"
  input:
    Resources:
      SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Inbound and outbound traffic for service
          GroupName: 'sample-secure-security-group'
          VpcId: !Ref vpcid
          SecurityGroupIngress:
          - IpProtocol: 'tcp'
            FromPort: 2456
            ToPort: 2458
            CidrIp: 0.0.0.0/0
            Description: 'Allow inbound traffic through port 2456-8'
  expectations:
    rules:
      security_group_dangerous_ports: PASS
```

With the issue being that this fails even though the port range within the test security group is not on the dangerous ports list. From the verbose output it looks like it evaluates all of the ports against both the greater than and less than conditions. 

i.e. in the test example 5432 < 2456 fails but then the second condition is evaluating 20 >2458 etc.

Although I may be interpreting the results incorrectly.
