### ISSUE TITLE
[GENERAL ISSUE] how to iterate through json list without knowing the key

### ISSUE THREAD

**Issue by dishikang123** [aws-cloudformation/cloudformation-guard#311]
**Describe the issue**
How do I reference/check the value of a json list if I don't know what the key is?

**Any examples**
For example:

The AWS::SSM::Parameter has Tags property that accepts type json.  Not knowing what the key values are going to be, I just want to check the value for certain patterns.   I tried 
`Properties.Tags[*] {  this == /<pattern>/}`
and it seems to resolve `this` as the entire list {"key1":"value1","key2":"value2"} and compares against regex pattern, which it fails.  I can make it work if I know what the key is `Properties.Tags["key"] == /<pattern>/`, but that's not the case in my scenario.

**Operating System:**
Amazon linux

**OS Version**

**Additional context**
cfn-guard v.2.1.2

**Comment by joshfried-aws** [comment]
Hi @dishikang123 

Given the following yaml file

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GuardLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: yourCustomRoleHere
      Tags:
        firstName: prod
```


this rule shows how we can check both keys and values. 

```
let aws_serverless_functions = Resources.*[ Type == 'AWS::Serverless::Function' ]

rule KEY_COMPLIANCE_CHECK when %aws_serverless_functions !empty {
  %aws_serverless_functions.Properties.Tags is_struct
  %aws_serverless_functions.Properties.Tags !empty

  # check the key ignoring capitalization/casing
  let key = %aws_serverless_functions.Properties.Tags[ keys == /^(?i)first([-|_])?name$/ ]

  # check the value 
  some %aws_serverless_functions.Properties.Tags.* == /^(?i)prod$/
  
  %key !empty
}
```

Please let me know if you have any other questions. 

Thanks,
