### ISSUE TITLE
[BUG] Missing colon after Ref in AWS::SQS::QueuePolicy Queues causes deployment problems

### ISSUE THREAD

**Issue by PeterPolestar** [aws-cloudformation/cloudformation-guard#318]
**Describe the bug**
Hi, I hope this is the right place for this. 
I've found a problem when a missing colon after (or ! before) for a queue policy queues ref field in the template causes the deployment and then deletion of the resource to fail and retrying three times when rolling back taking merely 3.5 hours before it finishes. 

**To Reproduce**
Add the following resource to your serverless yml:

```
MyQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'MyQueue'
  SqsToEventBridgePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt MyQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt MyQueue.Arn
      Queues:
        - Ref MyQueue

```
The problem with the template below is the missing colon in the last line which should be:

```      - Ref: MyQueue```
      

**Expected behavior**
I would expect the template parser to detect this and not trying to deploy.

**Operating System:**
Windows

**OS Version**
10

**Additional context**
