### ISSUE TITLE
[GENERAL ISSUE] Shouldn't `unresolved` be not `FAIL` but `ERROR` in unit testing?

### ISSUE THREAD

**Issue by yukihiko-shinoda** [aws-cloudformation/cloudformation-guard#367]
**Describe the issue**

In case when happen `unresolved`, AWS Config custom policy rule behaves as `SKIP`.
However, AWS CloudFormation Guard judges as `FAIL` in unit testing.

This causes missed confirmation in production for the pattern tested in unit testing process.

**Any examples**

`./guard-files/test.guard`:

```plaintext
foo == 1
```

`./guard-files/tests/test.yml`:

```yaml
- name: Succeed
  input:
    foo: 1
  expectations:
    rules:
      default: PASS
- name: Developer expects FAIL but mistaking Guard DSL coding in fact
  input:
    bar: 1
  expectations:
    rules:
      default: FAIL
```

Then, `cfn-guard test -d guard-files -v`:

```console
Testing Guard File guard-files/test.guard
Test Case #1
Name: Succeed
`- File(, Status=PASS)[Context=File(rules=1)]
   `- Rule(default, Status=PASS)[Context=default]
      `- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block foo EQUALS  1]
         `- GuardClauseValueCheck(Status=PASS)[Context= foo EQUALS  1]
  PASS Rules:
    default: Expected = PASS

Test Case #2
Name: Developer expects FAIL but mistaking Guard DSL coding in fact
`- File(, Status=FAIL)[Context=File(rules=1)]
   `- Rule(default, Status=FAIL)[Context=default]
      `- GuardClauseBlock(Status = FAIL)[Context=GuardAccessClause#block foo EQUALS  1]
         `- GuardClauseBinaryCheck(Status=FAIL, Comparison= EQUALS, from=(unresolved, Path=[L:0,C:0] Value={"bar":1}), to=)[Context= foo EQUALS  1]
  PASS Rules:
    default: Expected = FAIL
```

**Operating System:**

Debian GNU/Linux (Docker Container)

**OS Version**

11 (bullseye) (Docker Container)
