### ISSUE TITLE
Intrinsic functions handled differently when testing vs validating

### ISSUE THREAD

**Issue by caJaeger** [aws-cloudformation/cloudformation-guard#375]
**Describe the bug**

It seems that the handling of intrinsic functions is different when validating vs testing. The test endpoint doesn't seem to treat `!Sub` or `!Ref` as keys but rather strings in the value of the field.

The following will grab all resources with a `Runtime: !Ref Runtime` when validating, but if I provide the same data in a test it will be skipped like Runtime.Ref doesn't exist.

```
let parameterized_runtime_functions = Resources.*[
    Type == "AWS::Lambda::Function"
    Properties {
        Runtime.Ref exists
    }
]
```

**To Reproduce**
rule-file.guard:
```
let parameterized_runtime_functions = Resources.*[
    Type == "AWS::Lambda::Function"
    Properties {
        Runtime.Ref exists
    }
]

when %parameterized_runtime_functions !empty {
    let runtime_parameter_refs = %parameterized_runtime_functions.Properties.Runtime.Ref
    let runtime_parameters = Parameters.%runtime_parameter_refs
    %runtime_parameters {
        AllowedValues exists
        AllowedValues == ['nodejs']<<The parameter being referenced for Runtime must specify '["nodejs"]' for AllowedValues>>
    }
}
```

test-file.yml:
```
- input:
    Parameters:
      Runtime:
        Type: String
        AllowedValues:
          - nodejs

    Resources:
      Function:
        Type: AWS::Lambda::Function
        Properties:
          Runtime: !Ref Runtime

  expectations:
    rules:
      default: PASS
```

`cfn-guard test -r ./rule-file.guard -t ./test-file.yml`
```
Test Case #1
  FAIL Rules:
    default: Expected = PASS, Evaluated = [SKIP]
```

**Expected behavior**
I expect that the rule is not skipped because !Ref exists on the Runtime parameter:

```
Test Case #1
  PASS Rules:
    default: Expected = PASS
```

**Operating System:**
MacOS

**OS Version**
Monterey

**Additional**
Is there any documentation about how intrinsic functions are handled and best practices surrounding them?
