### ISSUE TITLE
Check on specific Key Value pair[GENERAL ISSUE]

### ISSUE THREAD

**Issue by AshutoshDahale** [aws-cloudformation/cloudformation-guard#380]
**Describe the issue**
I have a cfn template containing multiple Load balancers, they also contain their respective LoadBalancerAttributes.
The LoadBalancerAttributes is  bundle of Key value pairs, I am trying to check if a specific Key, value is always there in all LoadBalancerAttributes but I am not able to do that.

For E.g.
following is my sample template snippet, 

```
Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: AccessLogBucketPolicy
    Properties:
      IpAddressType: dualstack
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Ref AccessLogsBucket
        - Key: access_logs.s3.prefix
          Value: 'public'
```

I have tried the following guard rule command,

```
 #
# Ensure all application LB has alb-http-drop-invalid-header-enabled
#
rule drop_invalid_headers {
     let app_lb = Resources.*[
                Type == 'AWS::ElasticLoadBalancingV2::LoadBalancer'
                Properties.Type == 'application' <<<TO check all LB of type application>>>
            ]

    WHEN %app_lb !EMPTY {
           some %app_lb.Properties.LoadBalancerAttributes.*.Key == 'routing.http.drop_invalid_header_fields.enabled'
    }
}
```

As I mentioned I have multiple Load Balancers, by using the command if even 1 of them have this property it passes but I want to check all of the LB to have the Property, Please guide me how can I achieve this.
