### ISSUE TITLE
[Enhancement] Introduce Parameter Inputs for checking the CF scripts

### ISSUE THREAD

**Issue by konKeramaris** [aws-cloudformation/cloudformation-guard#39]
**Is your feature request related to a problem? Please describe.**
In its current form, cfn-guard checks the Cloudformation script without any input. 

Example, Lets say I have a Cloudformation script similar to the following (simplified version)
``` yaml
Parameters:
  RDSEncryption:
    Type: String

Resources:
  RDSPostgressDB:
    Type: AWS::RDS::DBInstance
    Properties: 
      StorageEncrypted: !Ref RDSEncryption
```

I want to create an RDS Database and I have a CF parameter input for encryption (true/false). Currently is no way currently in cfn-guard to verify that the RDS will be created using encryption. I can only verify the the StorageEncrypted will have the value "RDSEncryption" (please correct me if I'm wrong)

**Describe the solution you'd like**
I would prefer an option to provide a json document with the CF parameter inputs and be able to check the Cloudformation script after all those values have been implemented. 
The example I gave above would look like:

rules:
```
AWS::RDS::DBInstance StorageEncrypted == true
```

input.json:
``` json
[
  {
    "ParameterKey": "RDSEncryption",
    "ParameterValue": "true"
  }
]
```

cfn-guard:
``` bash
cargo run -- -t rds.yaml -r rules -i input.json
```
cfn-guard will change the `RDSEncryption` Rerefence with the input `true` and will be able to check against that
