### ISSUE TITLE
[BUG] cfn-guard error via GitHub Actions

### ISSUE THREAD

**Issue by Aaron-Garrett** [aws-cloudformation/cloudformation-guard#417]
**Describe the bug**
The cfn-guard rule runs appropriately on my local machine but not via GitHub Actions

**To Reproduce**
Please supply:

1. Example rules and template that results in the error
Rule: 
```
let aws_iam_entities_no_managed_policy = Resources.*[
  Type in [ /AWS::IAM::User/,
            /AWS::IAM::Role/,
            /AWS::IAM::Group/ ]
  Metadata.guard.SuppressedRules not exists or
  Metadata.guard.SuppressedRules.* != "IAM_ONLY_ALLOW_EDBManagedPolicies"
]

rule IAM_ONLY_ALLOW_EDBManagedPolicies when %aws_iam_entities_no_managed_policy !empty {
  when %aws_iam_entities_no_managed_policy.Properties.ManagedPolicyArns !empty  {
    %aws_iam_entities_no_managed_policy.Properties.ManagedPolicyArns[*]."Fn::Sub" != /^arn:aws:iam::\${AWS::AccountId}:policy\/AWS/
    <<
      Violation: Only select managed policies are allowed on IAM Users, Roles, or Groups.
      Fix: Remove the disallowed policies from any IAM Users, Roles, or Groups.
    >>
  }

}
```
Template:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation exports'

Resources: 
  TestingPolicy: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'GHA-GIS-Pipeline-${DeployEnvironment}'
      ManagedPolicyArns: 
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/foobar-kms-s3"
        - !Sub "arn:aws:iam::${AWS::AccountId}:policy/AWSCodeDeployRoleForLambda"
```
1. The commands you used to invoke the tool

        OUTPUT=`./cfn-guard-v2-ubuntu-latest/cfn-guard validate --show-summary pass,fail --data "$TEMPLATE_FILE" --rules .github/edb-pr-automation/lib/cfn-guard/rules/  2>&1`
        STATUS=$?

1. The output of a `-v` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the cfn-guard-lambda

![Screenshot 2023-11-21 at 3 26 38 PM](https://github.com/aws-cloudformation/cloudformation-guard/assets/111362443/64e42b93-fbfd-440d-8bf9-56914226517e)

**NOTE: Please be sure that the templates, rules and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**

I expected the result to return "FAIL" due to one of the Managed policy names starting with AWS

**Operating System:**
[eg, MacOS, Windows, Ubuntu, etc]

Ubuntu

**OS Version**
[eg Catalina, 10, 18.04, etc]

Latest on GitHub Actions

**Additional context**

It worked on the same branch, template, repo etc. on my local machine (Mac OS) utilizing the validate command, but it failed when running via GitHub Actions and the shell script command I put in above
