### ISSUE TITLE
[BUG] Failed rule does not print details of the failure

### ISSUE THREAD

**Issue by polothy** [aws-cloudformation/cloudformation-guard#443]
**Describe the bug**
When [this S3 rule](https://github.com/aws-cloudformation/aws-guard-rules-registry/blob/main/rules/aws/amazon_s3/s3_bucket_ssl_requests_only.guard) fails, `cfn-guard` only prints this as the output:

```
test-template2.yaml Status = FAIL
FAILED rules
s3_bucket_ssl_requests_only.guard/S3_BUCKET_SSL_REQUESTS_ONLY    FAIL
---
Evaluating data test-template2.yaml against rules s3_bucket_ssl_requests_only.guard
Number of non-compliant resources 0
```

And it doesn't print the more useful information about what resource is invalid and the error message.

**To Reproduce**

This template should fail the rule:

```yaml
Resources:
  ExampleS3:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AWSLogDeliveryWrite"
            Effect: "Allow"
            Principal:
              Service:
                - "delivery.logs.amazonaws.com"
            Action: "s3:PutObject"
            Resource: "*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
```

Here it is running with `-v` (`cfn-guard validate --rules rules/aws/amazon_s3/s3_bucket_ssl_requests_only.guard -d test-template2.yaml -v`):

```
test-template2.yaml Status = FAIL
FAILED rules
s3_bucket_ssl_requests_only.guard/S3_BUCKET_SSL_REQUESTS_ONLY    FAIL
---
Evaluating data test-template2.yaml against rules s3_bucket_ssl_requests_only.guard
Number of non-compliant resources 0
`- File(test-template2.yaml, Status=FAIL)[Context=File(rules=1)]
   `- Rule(S3_BUCKET_SSL_REQUESTS_ONLY, Status=FAIL)[Context=S3_BUCKET_SSL_REQUESTS_ONLY]
      |- Rule/When(Status=PASS)[Context=Rule#S3_BUCKET_SSL_REQUESTS_ONLY/When]
      |  `- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block %s3_buckets_policies_ssl_requests_only not EMPTY  ]
      |     |- Filter/ConjunctionsBlock(Status=PASS)[Context=Filter/Map#2]
      |     |  |- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block Type EQUALS  "AWS::S3::BucketPolicy"]
      |     |  |  `- GuardClauseValueCheck(Status=PASS)[Context= Type EQUALS  "AWS::S3::BucketPolicy"]
      |     |  `- Disjunction(Status = PASS)[Context=cfn_guard::rules::exprs::GuardClause#disjunction]
      |     |     `- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block Metadata.guard.SuppressedRules not EXISTS  ]
      |     |        `- GuardClauseValueCheck(Status=PASS)[Context= Metadata.guard.SuppressedRules not EXISTS  ]
      |     `- GuardClauseValueCheck(Status=PASS)[Context= %s3_buckets_policies_ssl_requests_only not EMPTY  ]
      `- GuardClauseBlock(Status = FAIL)[Context=GuardAccessClause#block %ssl_secure_bucket_policies not EMPTY  ]
         |- Filter/ConjunctionsBlock(Status=FAIL)[Context=Filter/Map#1]
         |  `- GuardValueBlockCheck(Status = FAIL)[Context=BlockGuardClause#Location[file:s3_bucket_ssl_requests_only.guard, line:36, column:3]]
         |     `- GuardValueBlockCheck(Status = FAIL)[Context=BlockGuardClause#Location[file:s3_bucket_ssl_requests_only.guard, line:37, column:5]]
         |        |- GuardClauseBlock(Status = FAIL)[Context=GuardAccessClause#block Effect EQUALS  "Deny"]
         |        |  `- GuardClauseBinaryCheck(Status=FAIL, Comparison= EQUALS, from=(resolved, Path=/Resources/ExampleS3/Properties/PolicyDocument/Statement/0/Effect[L:9,C:20] Value="Allow"), to=(resolved, Path=[L:0,C:0] Value="Deny"))[Context= Effect EQUALS  "Deny"]
         |        `- GuardValueBlockCheck(Status = FAIL)[Context=BlockGuardClause#Location[file:s3_bucket_ssl_requests_only.guard, line:39, column:7]]
         |           `- GuardClauseBlock(Status = FAIL)[Context=GuardAccessClause#block Bool.aws:SecureTransport EQUALS  false]
         |              `- GuardClauseBinaryCheck(Status=FAIL, Comparison= EQUALS, from=(unresolved, Path=/Resources/ExampleS3/Properties/PolicyDocument/Statement/0/Condition[L:16,C:14] Value={"StringEquals":{"s3:x-amz-acl":"bucket-owner-full-control"}}), to=)[Context= Bool.aws:SecureTransport EQUALS  false]
         `- GuardClause(Status=FAIL, Empty, 
    Violation: Bucket policies must feature a statement to enforce TLS usage.
    Fix: Set a bucket policy statement to '"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":"*","Condition":{"Bool":{"aws:SecureTransport":false}}' .
  )[Context= %ssl_secure_bucket_policies not EMPTY  ]
```

**Expected behavior**

Would like to see a report on the CloudFormation resources that failed the check and the error message. For example, when other rules fail, they produce this sort of output:

```
Resource = MyBucket {
  Type      = AWS::S3::Bucket
  CDK-Path  = my-stack/Bucket/Resource
  Rule = S3_BUCKET_SSL_REQUESTS_ONLY {
...etc
```

**Operating System:**
MacOS

**OS Version**
Sonoma

**Additional context**
None.
