### ISSUE TITLE
[GENERAL ISSUE] String concatenation with literal and variable

### ISSUE THREAD

**Issue by jkruse14** [aws-cloudformation/cloudformation-guard#485]
**Describe the issue**
A clear and concise description of what the issue is.

There does not seem to be a way to combine two strings, either inline or through variable definition, to allow for the combination of a string literal and a variable

**Any examples**

```
let bucket_name = "s3/%BucketName"
LoggingConfiguration.LogFilePrefix == %bucket_name
```

```
let bucket_name = "s3/"+%BucketName
LoggingConfiguration.LogFilePrefix == %bucket_name
```

```
LoggingConfiguration.LogFilePrefix == "s3/"+%BucketName
```

Version
```
> cfn-guard --version
cfn-guard 3.0.3
```
**Operating System:**
Windows

**OS Version**
Windows 10 Pro

**Additional context**
The outcome I would like to achieve in my specific context is to create a rule that enforces the `LoggingConfiguration.LogFilePrefix` of an S3 Bucket to match the pattern of `s3/<bucket name>`, so if I have this configuration:

```
Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cfn-guard-test-${AWS::AccountId}-${AWS::Region}
      ...
      LoggingConfiguration:
        DestinationBucketName: !Sub dibh-${AWS::AccountId}-${AWS::Region}-common-logging
        LogFilePrefix: !Sub s3/cfn-guard-test-${AWS::AccountId}-${AWS::Region}
```

I could write something like
```
let log_file_prefix = "s3/"+BucketName
LoggingConfiguration.LogFilePrefix == %log_file_prefix
```
or with a function
```
let log_file_prefix = join_strings(["s3", BucketName], "/")
LoggingConfiguration.LogFilePrefix == %log_file_prefix
```
