### ISSUE TITLE
[Enhancement] Create example explaining that strict checking means missing resources properties and expected error.

### ISSUE THREAD

**Issue by Rob-El** [aws-cloudformation/cloudformation-guard#51]
When I started using cfn-guard (by the way, love the tool!), it took awhile to figure out if it would fail if a required resource property was completely missing.  It's not completely obvious (well, to me at least) that "strict" equates to missing CloudFormation resource properties. 

The Readme.md file is not easy to parse, and it took a few times reading through it to understand how the tool works.  I actually figured out how strict works from a closed issue request.

I think it would help tremendously to include an example where (and why) strict is used, and what the output looks like for a failure.

For instance, I wanted to validate an EC2 Launch Template where EBS encryption is mandated.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
    SampleLaunchTemplate:
        Type: "AWS::EC2::LaunchTemplate"
        Properties:
            LaunchTemplateData:
                BlockDeviceMappings:
                    Ebs:
                        Encrypted: true
```

with a ruleset file such as...

```
let encryption_flag = true

AWS::EC2::LaunchTemplate LaunchTemplateData.BlockDeviceMappings.Ebs.Encrypted == %encryption_flag
```

For the example, something like...

"In the example above, use strict (-s) to determine if a resource property is completely missing, such as removing the BlockDeviceMappings section".  See below.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
    SampleLaunchTemplate:
        Type: "AWS::EC2::LaunchTemplate"
        Properties:
            LaunchTemplateData:
```

Sample command:
```
>cargo run -- -t ec2launchtemplate-template.yaml -r ec2launchtemplate.ruleset -s
```

Sample result

```
[SampleLaunchTemplate] failed because it does not contain the required property of [BlockDeviceMappings]
Number of failures: 1
```

Many thanks!
