### ISSUE TITLE
[BUG] When using cfn-guard with pre-commit, repeated `--rules` are ignored

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#539]
**Describe the bug**
When using a pre-commit configuration where --rules is repeated in the args section, only the first ruleset is used:

**To Reproduce**
Use this in `.pre-commit-config.yaml` and create both rule files:

```yaml
repos:
  - repo: https://github.com/aws-cloudformation/cloudformation-guard
    rev: action-v0.0.4
    hooks:
      - id: cfn-guard
        args:
          - --operation=validate
          - --rules=../guard-rules-test/wa-Reliability-Pillar.guard
          - --rules=../guard-rules-test/wa-Security-Pillar.guard
        files: ^templates/.*\.yaml
```

**Expected behavior**
Both rule files should be used

**Additional context**
Guard supports repeats of the --rules option, and the python argument parsers for the hook does to. The issue seems to be https://github.com/aws-cloudformation/cloudformation-guard/blob/main/pre_commit_hooks/cfn_guard.py#L155 .

Currently the code there is:

```python
cmd = f"validate --rules={args.rules[0]} --data={filename}"
```

It should probably be similar to

```python
rules_args = " ".join([f"--rules={r}" for r in args.rules])
cmd = f"validate {rules_args} --data={filename}"
```

There is a similar problem in the code for args.operation and args.dir.
Since they cannot be repeated, I recommend not using append when defining the argument for both of them
