### ISSUE TITLE
[BUG] Error encountered while parsing data file when using yaml anchor

### ISSUE THREAD

**Issue by sj-versent** [aws-cloudformation/cloudformation-guard#578]
**Describe the bug**

When validating a source file of type YAML, if yaml anchors are in use then cfn-guard fails to parse the file and errors with `Error occurred Parser Error`

**To Reproduce**
1. Source File

```yaml
---

homeRegion: &HOME_REGION ap-southeast-2

vpcs:
  - name: myvpc
    tags:
      - key: Name
        value: myvpc
    account: myaccount
    region: *HOME_REGION
    defaultSecurityGroupRulesDeletion: true
 ```

1. Rule file

```json
rule check_defaultSecurityGroupRulesDeletion {
    vpcs.defaultSecurityGroupRulesDeletion == true
}
```

1. The commands you used to invoke the tool

```bash
cfn-guard validate --data original.yaml --rules rule.guard
```

1. The output of a `-v` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the cfn-guard-lambda

```
cfn-guard validate -v  --data original.yaml --rules rule.guard
Error occurred Parser Error when parsing `Error encountered while parsing data file: original.yaml, data beginning with 
---

homeRegion: &HOME_REGION ap-southeast-2

vpcs:
  - name: myvpc
    tags:
      - key: Name
    
 ...`

```

**Expected behavior**

File is parsed correctly and rules triggered if appropraite

**Operating System:**

MacOS

**OS Version**

15.0.1 - Sequoia

**Additional context**

Commenting out the YAML anchor in the source file enables cfn-guard to process the file.
