### ISSUE TITLE
[GENERAL ISSUE] Rules not triggering when using AWS Config with Lambda

### ISSUE THREAD

**Issue by smparekh** [aws-cloudformation/cloudformation-guard#603]
I am using the Landing Zone Accelerator in US GovCloud (v2.1.4) but need to exclude its resources from AWS Config, these resources are tagged with a Key: `Accelerator`

Using Guard Rules to validate lambda inside VPC I have this ruleset:
```
let ignored_tags = [ "Accelerator", "NoAlert" ]

rule resource_is_lambda {
    resourceType == "AWS::Lambda::Function" <<Resource must be a Lambda Function>>
}

rule lambda_inside_vpc when resource_is_lambda {
    when tags exists {
        let lambda_tags = tags[*].Key
        when %lambda_tags not in %ignored_tags {
            configuration.vpcConfig exists <<Lambda Function must be inside a VPC>>
            configuration.vpcConfig.subnetIds exists
            configuration.vpcConfig.securityGroupIds exists
        }
    } OR
    when tags !exists {
        configuration.vpcConfig exists <<Lambda Function must be inside a VPC>>
        configuration.vpcConfig.subnetIds exists
        configuration.vpcConfig.securityGroupIds exists
    }
}
```
A dummy config change notification where I change a tag `Env` from `dev` to `prod`

```
{
    "version": "0",
    "id": "f54ab413-042b-e578-02f3-b40f45b47c21",
    "detail-type": "Config Configuration Item Change",
    "source": "aws.config",
    "account": "xxxx",
    "time": "2025-01-22T22:41:05Z",
    "region": "us-gov-west-1",
    "resources": [
        "arn:aws-us-gov:lambda:us-gov-west-1:xxxx:function:test-function"
    ],
    "detail": {
        "recordVersion": "1.3",
        "messageType": "ConfigurationItemChangeNotification",
        "configurationItemDiff": {
            "changedProperties": {
                "Configuration.lastModified": {
                    "previousValue": "2025-01-22T21:57:51.402+0000",
                    "updatedValue": "2025-01-22T22:39:17.029+0000",
                    "changeType": "UPDATE"
                },
                "Configuration.revisionId": {
                    "previousValue": "034bdd4a-c82f-49f1-8b1a-9390d4ff6de1",
                    "updatedValue": "7a555563-3fa0-475a-86fd-e9ba3bed2cb3",
                    "changeType": "UPDATE"
                },
                "Tags.0": {
                    "previousValue": "prod",
                    "updatedValue": "dev",
                    "changeType": "UPDATE"
                },
                "SupplementaryConfiguration.Tags.0": {
                    "previousValue": "prod",
                    "updatedValue": "dev",
                    "changeType": "UPDATE"
                }
            },
            "changeType": "UPDATE"
        },
        "notificationCreationTime": "2025-01-22T22:41:05.836Z",
        "configurationItem": {
            "relatedEvents": [],
            "relationships": [
                {
                    "resourceName": "test-function-role-d76fbjlt",
                    "resourceType": "AWS::IAM::Role",
                    "name": "Is associated with "
                }
            ],
            "configuration": {
                "functionName": "test-function",
                "functionArn": "arn:aws-us-gov:lambda:us-gov-west-1:xxxx:function:test-function",
                "runtime": "nodejs22.x",
                "role": "arn:aws-us-gov:iam::xxxx:role/service-role/test-function-role-d76fbjlt",
                "handler": "index.handler",
                "codeSize": 295,
                "description": "",
                "timeout": 3,
                "memorySize": 128,
                "lastModified": "2025-01-22T22:39:17.029+0000",
                "codeSha256": "q8E7Nexf5xxhKT9/d4bGpAYOXJYFAUjJ0UDj8OivK8E=",
                "version": "$LATEST",
                "tracingConfig": {
                    "mode": "PassThrough"
                },
                "revisionId": "7a555563-3fa0-475a-86fd-e9ba3bed2cb3",
                "layers": [],
                "state": "Active",
                "lastUpdateStatus": "Successful",
                "fileSystemConfigs": [],
                "packageType": "Zip",
                "architectures": [
                    "arm64"
                ],
                "ephemeralStorage": {
                    "size": 512
                },
                "snapStart": {
                    "applyOn": "None",
                    "optimizationStatus": "Off"
                },
                "runtimeVersionConfig": {
                    "runtimeVersionArn": "arn:aws-us-gov:lambda:us-gov-west-1::runtime:64db813a1f0e478890d48dd6cf2e85e61f1de415620da94e3be62ee588121d0b"
                },
                "loggingConfig": {
                    "logFormat": "Text",
                    "logGroup": "/aws/lambda/test-function"
                }
            },
            "supplementaryConfiguration": {
                "Tags": {
                    "Env": "dev"
                }
            },
            "tags": {
                "Env": "dev"
            },
            "configurationItemVersion": "1.3",
            "configurationItemCaptureTime": "2025-01-22T22:41:05.254Z",
            "configurationStateId": 1737585665254,
            "awsAccountId": "x",
            "configurationItemStatus": "OK",
            "resourceType": "AWS::Lambda::Function",
            "resourceId": "test-function",
            "resourceName": "test-function",
            "ARN": "arn:aws-us-gov:lambda:us-gov-west-1:xxxx:function:test-function",
            "awsRegion": "us-gov-west-1",
            "availabilityZone": "Not Applicable",
            "configurationStateMd5Hash": ""
        }
    }
}
```

Rule log:
```
ConfigRuleId: config-rule-jylxid, ResourceType: AWS::Lambda::Function, ResourceId: test-function
{
    "not_compliant": {},
    "not_applicable": [
        "lambda_inside_vpc"
    ],
    "compliant": [
        "resource_is_lambda"
    ]
}
```

I am not sure why `lambda_inside_vpc` would not be applicable as in testing, the same skeleton works

Test file:
```
---
- name: Test Resource Type
  input:
    resourceType: AWS::IAM::Role
    configuration: { }
  expectations:
    rules:
      resource_is_lambda: FAIL
      lambda_inside_vpc: SKIP
- name: Test Lambda with ignored tag Accelerator
  input:
    resourceType: AWS::Lambda::Function
    tags:
      - Key: Accelerator
        Value: AWSAccelerator
    configuration: { }
  expectations:
    rules:
      resource_is_lambda: PASS
      lambda_inside_vpc: SKIP
- name: Test Lambda without ignored tag and no VPCConfig
  input:
    resourceType: AWS::Lambda::Function
    tags:
      - Key: Env
        Value: dev
    configuration: { }
  expectations:
    rules:
      resource_is_lambda: PASS
      lambda_inside_vpc: FAIL

- name: Test Lambda with VPCConfig
  input:
    resourceType: AWS::Lambda::Function
    configuration:
      vpcConfig:
        securityGroupIds: ["sg-12345678"]
        subnetIds: ["subnet-12345678"]
    tags:
      - Key: Env
        Value: dev
  expectations:
    rules:
      resource_is_lambda: PASS
      lambda_inside_vpc: PASS
- name: Test Lambda with VPCConfig and no tags
  input:
    resourceType: AWS::Lambda::Function
    configuration:
      vpcConfig:
        securityGroupIds: [ "sg-12345678" ]
        subnetIds: [ "subnet-12345678" ]
  expectations:
    rules:
      resource_is_lambda: PASS
      lambda_inside_vpc: PASS
- name: Test Lambda with no VPCConfig and no tags
  input:
    resourceType: AWS::Lambda::Function
    configuration:
      functionName: "test"
  expectations:
    rules:
      resource_is_lambda: PASS
      lambda_inside_vpc: FAIL
```

Test Results:
```
Test Case #1
Name: Test Resource Type
  PASS Rules:
    lambda_inside_vpc: Expected = SKIP
    resource_is_lambda: Expected = FAIL

Test Case #2
Name: Test Lambda with ignored tag Accelerator
  PASS Rules:
    resource_is_lambda: Expected = PASS
    lambda_inside_vpc: Expected = SKIP

Test Case #3
Name: Test Lambda with ignored tag VantaNoAlert
  PASS Rules:
    lambda_inside_vpc: Expected = SKIP
    resource_is_lambda: Expected = PASS

Test Case #4
Name: Test Lambda with ignored tag QuindarNoAlert
  PASS Rules:
    resource_is_lambda: Expected = PASS
    lambda_inside_vpc: Expected = SKIP

Test Case #5
Name: Test Lambda with ignored tags
  PASS Rules:
    lambda_inside_vpc: Expected = SKIP
    resource_is_lambda: Expected = PASS

Test Case #6
Name: Test Lambda without ignored tag and no VPCConfig
  PASS Rules:
    lambda_inside_vpc: Expected = FAIL
    resource_is_lambda: Expected = PASS

Test Case #7
Name: Test Lambda with VPCConfig
  PASS Rules:
    resource_is_lambda: Expected = PASS
    lambda_inside_vpc: Expected = PASS

Test Case #8
Name: Test Lambda with VPCConfig and no tags
  PASS Rules:
    lambda_inside_vpc: Expected = PASS
    resource_is_lambda: Expected = PASS

Test Case #9
Name: Test Lambda with no VPCConfig and no tags
  PASS Rules:
    lambda_inside_vpc: Expected = FAIL
    resource_is_lambda: Expected = PASS
```
