### ISSUE TITLE
[BUG] Not able to locate elements when Fn::ForEach loop is used in template

### ISSUE THREAD

**Issue by mwalesa89** [aws-cloudformation/cloudformation-guard#614]
**Describe the bug**
Guard is not able to find attributes that are created in cloudformation template using the Fn::ForEach loop

**To Reproduce**
Template: 
```
Resources:
  "Fn::ForEach::AuxiliaryBuckets":
    - Service
    - [athena, emr, glue, datasync]
    - "&{Service}S3Bucket":
        #Docu: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
        Type: AWS::S3::Bucket
        Properties:
          BucketName: !Join ["-",[!Ref Project, !Ref Environment, !Ref Service, !Ref AWS::AccountId]]
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
                  KMSMasterKeyID: !Ref KEY
                BucketKeyEnabled: true
          IntelligentTieringConfigurations:
            - Id: IntelligentTieringBucket
              Status: Enabled
              Tierings: 
                - AccessTier: ARCHIVE_ACCESS
                  Days: 180 #Dummy values to be changes when finalized
          LifecycleConfiguration:
            Rules:
              - Id: MoveObjectToIntelligentTiering
                Status: Enabled
                Transitions:
                  - StorageClass: INTELLIGENT_TIERING
                    TransitionInDays: 365 #Dummy values to be changed when finalized
          VersioningConfiguration:
            Status: Enabled
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
```
```
Guard variable:
`let s3_bucket = Resources.*[Type == "AWS::S3::Bucket"]`
```

Variable is empty, and it's not possible to validate values after the for Each loop

**Expected behavior**
Defined variable should be able to locate the resource, to ensure later validation af static fields

**Operating System:**
MAC/windows

**OS Version**

**Additional context**
