### ISSUE TITLE
[BUG] Suppression Rules Ignored For Certain Checks

### ISSUE THREAD

**Issue by SyphonxZA** [aws-cloudformation/cloudformation-guard#636]
**Describe the bug**
Suppression rules on resources are being ignored for certain rules, resulting in a template failing validation. Most suppression rules are adhered and do not result in failures.

**To Reproduce**
Please supply:

```
Resources:
  ElasticContainerTaskExecutionRole:
    Type: AWS::IAM::Role
    Metadata:
      guard:
        SuppressedRules:
        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: task-execution-role
```

Command:
```
cfn-guard validate --rules /home/redacted/development/aws-guard-rules-registry/rules/aws --data /home/redacted/development/ecs/task/product.template
```

Result:
```
/home/redacted/development/ecs/task/product.template Status = FAIL
FAILED rules
cfn_no_explicit_resource_names.guard/CFN_NO_EXPLICIT_RESOURCE_NAMES    FAIL
---
Evaluating data /home/redacted/development/ecs/task/product.template against rules cfn_no_explicit_resource_names.guard
Number of non-compliant resources 2
Resource = ElasticContainerTaskExecutionRole {
  Type      = AWS::IAM::Role
  Rule = CFN_NO_EXPLICIT_RESOURCE_NAMES {
    ALL {
      Check =  RoleName EMPTY   {
        ComparisonError {
          Error            = Check was not compliant as property [/Resources/ElasticContainerTaskExecutionRole/Properties/RoleName[L:309,C:16]] was not empty.
          PropertyPath    = /Resources/ElasticContainerTaskExecutionRole/Properties/RoleName[L:309,C:16]
          Operator        = EMPTY
          Code:
              307.            Service: ecs-tasks.amazonaws.com
              308.      ManagedPolicyArns:
              309.      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
              310.      RoleName: !Sub ${StackNameTag}-execution-role-${AWS::Region}
              311.
              312.  ExternalRecordSet:

        }
      }
    }
  }
}
```

**Expected behavior**
Suppressing a rule on a resource should not result in failures.

**Operating System:**
Ubuntu

**OS Version**
24.04

**Comment by SyphonxZA** [comment]
@joshfried-aws currently I am using the rules from this repo: https://github.com/aws-cloudformation/aws-guard-rules-registry

```
#
#####################################
##          AWS Solutions          ##
#####################################
# Rule Identifier:
#   CFN_NO_EXPLICIT_RESOURCE_NAMES
#
# Description:
#   Checks that the template does not explicitely name resources.
#
# Reports on:
#   Various
#
# Evaluates:
#   AWS CloudFormation
#
# Rule Parameters:
#   NA
#
# CFN_NAG Rule Id:
#   W28
#
# Scenarios:
# a) SKIP: when none of the covered resources types are present
# b) PASS: when none of the applicable types have static resource names
# c) FAIL: when any applicable types has a static resource name
# d) SKIP: when metada has rule suppression for CFN_NO_EXPLICIT_RESOURCE_NAMES or CFN_NAG W28

let applicable_types = [
  "AWS::ApiGateway::ApiKey",
  "AWS::CloudWatch::Alarm",
  "AWS::CodeDeploy::DeploymentConfig",
  "AWS::CodeDeploy::DeploymentGroup",
  "AWS::DynamoDB::Table",
  "AWS::EC2::SecurityGroup",
  "AWS::ECR::Repository",
  "AWS::ElasticLoadBalancingV2::LoadBalancer",
  "AWS::Elasticsearch::Domain",
  "AWS::IAM::Group",
  "AWS::IAM::ManagedPolicy",
  "AWS::IAM::Role",
  "AWS::Kinesis::Stream",
  "AWS::RDS::DBInstance"
]

# Select applicable resources less suppressed resources
let cloudformation_no_static_name_resources = Resources.*[Type in %applicable_types
  Metadata.cfn_nag.rules_to_suppress not exists or
  Metadata.cfn_nag.rules_to_suppress.*.id != "W28"
  Metadata.guard.SuppressedRules not exists or
  Metadata.guard.SuppressedRules.* != "CFN_NO_EXPLICIT_RESOURCE_NAMES"
]

rule CFN_NO_EXPLICIT_RESOURCE_NAMES
  when %cloudformation_no_static_name_resources !empty {
    AWS::ApiGateway::ApiKey {
      Properties{
        Name empty
      }
    }
    AWS::CloudWatch::Alarm {
      Properties{
        AlarmName empty
      }
    }
    AWS::CodeDeploy::DeploymentConfig {
      Properties{
        DeploymentConfigName empty
      }
    }
    AWS::CodeDeploy::DeploymentGroup {
      Properties{
        DeploymentGroupName empty
      }
    }
    AWS::DynamoDB::Table {
      Properties{
        TableName empty
      }
    }
    AWS::EC2::SecurityGroup {
      Properties{
        GroupName empty
      }
    }
    AWS::ECR::Repository {
      Properties{
        RepositoryName empty
      }
    }
    AWS::ElasticLoadBalancingV2::LoadBalancer {
      Properties{
        Name empty
      }
    }
    AWS::Elasticsearch::Domain {
      Properties{
        DomainName empty
      }
    }
    AWS::IAM::Group {
      Properties{
        GroupName empty
      }
    }
    AWS::IAM::ManagedPolicy {
      Properties{
        ManagedPolicyName empty
      }
    }
    AWS::IAM::Role {
      Properties{
        RoleName empty
      }
    }
    AWS::Kinesis::Stream {
      Properties{
        Name empty
      }
    }
    AWS::RDS::DBInstance {
      Properties{
        DBInstanceIdentifier empty
      }
    }
    %cloudformation_no_static_name_resources not empty
    <<
      Violation: Resource found with an explicit name, this disallows updates that require replacement of this resource.
      Fix: Remove static name from the resource
    >>
}
```

**Comment by SyphonxZA** [comment]
Hi @joshfried-aws , I only provided the role portion of the problematic template as the violations indicated that was the cause. I see now that the roles by themselves work fine with suppression.

I did some more digging on the full template and identified the actual resource causing the issue. In the template below it will fail if `CFN_NO_EXPLICIT_RESOURCE_NAMES` is not suppressed on the Security Group. However the results indicate the roles are the problem, the finding should be for the Sec Group.

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Elastic Container Service HTTP service and task.

Parameters:
  EcsClusterName:
    Type: String
    Description: The name of the ECS Cluster
  StackNameTag:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Specify the VPC ID.

Resources:
  ElasticContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      guard:
        SuppressedRules:
        - EC2_SECURITY_GROUP_EGRESS_OPEN_TO_WORLD_RULE # For Web traffic
        - SECURITY_GROUP_EGRESS_PORT_RANGE_RULE # For Web traffic
        # - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
    Properties:
      GroupDescription: VPC Security Group
      SecurityGroupEgress:
      - Description: ALLOW all TO all
        CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
      SecurityGroupIngress:
      - Description: !Sub ALLOW http FROM ${EcsClusterName}-external-alb
        FromPort: 80
        IpProtocol: tcp
        SourceSecurityGroupId: !Sub "{{resolve:ssm:/${VpcId}/security/security-groups/security-group-id/${EcsClusterName}-external-alb}}"
        ToPort: 80
      Tags:
      - Key: Name
        Value: !Sub ${StackNameTag}-instance-security-group
      VpcId: !Ref VpcId

  ElasticContainerTaskRole:
    Type: AWS::IAM::Role
    Metadata:
      guard:
        SuppressedRules:
        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
        - IAM_NO_INLINE_POLICY_CHECK # No inherent security issue using inline policies
        - IAM_POLICYDOCUMENT_NO_WILDCARD_RESOURCE # Selected actions only support the all resources wildcard('*').
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      Path: /
      Policies:
      - PolicyName: allow-ssmmessages-access-policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - ssmmessages:CreateControlChannel
            - ssmmessages:CreateDataChannel
            - ssmmessages:OpenControlChannel
            - ssmmessages:OpenDataChannel
            Resource: "*"
      RoleName: !Sub ${StackNameTag}-task-role-${AWS::Region}

  ElasticContainerTaskExecutionRole:
    Type: AWS::IAM::Role
    Metadata:
      guard:
        SuppressedRules:
        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: !Sub ${StackNameTag}-execution-role-${AWS::Region}
```

**Comment by SyphonxZA** [comment]
Removing the Tags property (only place with a 'Name') from the Security Group does not prevent the finding. So not sure what on the Security Group is triggering the issue.....

**Comment by SyphonxZA** [comment]
When specifying the `GroupName` property on the Security Group (without suppressing the rule) the findings correctly include the Security Group. However they ignore the suppression on the roles and thus 3 findings are generated instead of 1. Suppressing the rule on all 3 resources works as expected.

**Comment by johanmynhardt** [comment]
Ah, I see the issue, and below are the steps to reproduce:

- Start with `01-product-must-fail.template` that rightly fails
- Update `02-product-must-pass.template` to suppress `CFN_NO_EXPLICIT_RESOURCE_NAMES` on `Resources.ElasticContainerTaskExecutionRole`, and the expected outcome is true
- Update `03-product-must-pass-unrelated-suppression.template` to remove suppression of `CFN_NO_EXPLICIT_RESOURCE_NAMES` on `Resources.ElasticContainerSecurityGroup`
  - Observe failure on `/Resources/ElasticContainerTaskExecutionRole/Properties/RoleName` for `CFN_NO_EXPLICIT_RESOURCE_NAMES`

Starting with initial file:

```yaml
## 01-product-must-fail.template
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Elastic Container Service HTTP service and task.

Parameters:
  EcsClusterName:
    Type: String
    Description: The name of the ECS Cluster
  StackNameTag:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Specify the VPC ID.

Resources:
  ElasticContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      guard:
        SuppressedRules:
        - EC2_SECURITY_GROUP_EGRESS_OPEN_TO_WORLD_RULE # For Web traffic
        - SECURITY_GROUP_EGRESS_PORT_RANGE_RULE # For Web traffic
        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
    Properties:
      GroupDescription: VPC Security Group
      SecurityGroupEgress:
      - Description: ALLOW all TO all
        CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
      SecurityGroupIngress:
      - Description: !Sub ALLOW http FROM ${EcsClusterName}-external-alb
        FromPort: 80
        IpProtocol: tcp
        SourceSecurityGroupId: !Sub "{{resolve:ssm:/${VpcId}/security/security-groups/security-group-id/${EcsClusterName}-external-alb}}"
        ToPort: 80
      Tags:
      - Key: Name
        Value: !Sub ${StackNameTag}-instance-security-group
      VpcId: !Ref VpcId

  ElasticContainerTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: !Sub ${StackNameTag}-execution-role-${AWS::Region}
```

Testing:

> `cfn-guard validate --rules rule-issue-636.guard -o yaml -d 01-product-must-fail.template`

```bash
/tmp/cfn-guard/01-product-must-fail.template Status = FAIL
FAILED rules
rule-issue-636.guard/CFN_NO_EXPLICIT_RESOURCE_NAMES    FAIL
````

```yaml
name: /tmp/cfn-guard/01-product-must-fail.template
metadata: {}
status: FAIL
not_compliant:
- Rule:
    name: CFN_NO_EXPLICIT_RESOURCE_NAMES
    metadata: {}
    messages:
      custom_message: null
      error_message: null
    checks:
    - Clause:
        Unary:
          check:
            Resolved:
              value:
                path: /Resources/ElasticContainerTaskExecutionRole/Properties/RoleName
                value:
                  Fn::Sub: ${StackNameTag}-execution-role-${AWS::Region}
              comparison:
              - Empty
              - false
          context: ' RoleName EMPTY  '
          messages:
            custom_message: ''
            error_message: Check was not compliant as property [/Resources/ElasticContainerTaskExecutionRole/Properties/RoleName[L:53,C:16]] was not empty.
not_applicable: []
compliant: []
```

Then apply the change: 

```diff
## 02-product-must-pass.template
--- 01-product-must-fail.template       2025-05-15 14:20:53.349662421 +0200
+++ 02-product-must-pass.template       2025-05-15 14:08:09.459846270 +0200
@@ -41,6 +41,10 @@

   ElasticContainerTaskExecutionRole:
     Type: AWS::IAM::Role
+    Metadata:
+      guard:
+        SuppressedRules:
+        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Suppresses failure on `RoleName`
     Properties:
       AssumeRolePolicyDocument:
         Statement:
```

Testing:

> `cfn-guard validate --rules rule-issue-636.guard -o yaml -d 02-product-must-pass.template`

```yaml
name: /tmp/cfn-guard/02-product-must-pass.template
metadata: {}
status: SKIP
not_compliant: []
not_applicable:
- CFN_NO_EXPLICIT_RESOURCE_NAMES
compliant: []
```

Then remove the `CFN_NO_EXPLICIT_RESOURCE_NAMES` suppression for an **unrelated** resource:

```diff
## 03-product-must-pass-unrelated-suppression.template
--- 02-product-must-pass.template       2025-05-15 14:08:09.459846270 +0200
+++ 03-product-must-pass-unrelated-suppression.template 2025-05-15 14:10:01.059793379 +0200
@@ -19,7 +19,6 @@
         SuppressedRules:
         - EC2_SECURITY_GROUP_EGRESS_OPEN_TO_WORLD_RULE # For Web traffic
         - SECURITY_GROUP_EGRESS_PORT_RANGE_RULE # For Web traffic
-        - CFN_NO_EXPLICIT_RESOURCE_NAMES # Needlessly restrictive
     Properties:
       GroupDescription: VPC Security Group
       SecurityGroupEgress:
```

Testing, expecting no failure, but failure reported on **unrelated** resource:

> `cfn-guard validate --rules rule-issue-636.guard -o yaml -d 03-product-must-pass-unrelated-suppression.template`

```bash
/tmp/cfn-guard/03-product-must-pass-unrelated-suppression.template Status = FAIL
FAILED rules
rule-issue-636.guard/CFN_NO_EXPLICIT_RESOURCE_NAMES    FAIL
```
```yaml
name: /tmp/cfn-guard/03-product-must-pass-unrelated-suppression.template
metadata: {}
status: FAIL
not_compliant:
- Rule:
    name: CFN_NO_EXPLICIT_RESOURCE_NAMES
    metadata: {}
    messages:
      custom_message: null
      error_message: null
    checks:
    - Clause:
        Unary:
          check:
            Resolved:
              value:
                path: /Resources/ElasticContainerTaskExecutionRole/Properties/RoleName
                value:
                  Fn::Sub: ${StackNameTag}-execution-role-${AWS::Region}
              comparison:
              - Empty
              - false
          context: ' RoleName EMPTY  '
          messages:
            custom_message: ''
            error_message: Check was not compliant as property [/Resources/ElasticContainerTaskExecutionRole/Properties/RoleName[L:56,C:16]] was not empty.
not_applicable: []
compliant: []
```

Unfortunately I'm extremely new to the internal workings of guard rules so can't quite figure out why it's behaving like this.
