### ISSUE TITLE
[Enhancement] Regular expression inside json

### ISSUE THREAD

**Issue by eRaMvn** [aws-cloudformation/cloudformation-guard#78]
**Is your feature request related to a problem? Please describe.**
I want to say thank you for this great tool. I tried to use regular expression in inside json, but it did not work

**Describe the solution you'd like**
I have the following policy:

```
{
    "Description": "Create Test Role",
    "Parameters": {
        "KmsDataKeyArn": {
            "Description": "Test",
            "Type": "String"
        }
    },
    "Resources": {
        "TestRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "TestPolicyDocument",
                            "Effect": "Allow",
                            "Principal": {
                                "AWS": [
                                    {
                                        "Fn::Sub": "${AWS::AccountId}"
                                    }
                                ],
                                "Service": [
                                    "iam.amazonaws.com",
                                    "ec2.amazonaws.com"
                                ]
                            },
                            "Action": "sts:AssumeRole"
                        }
                    ]
                },
                "Path": "/",
                "Policies": [
                    {
                        "PolicyName": "TestPolicy",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Sid": "ACMPA",
                                    "Effect": "Allow",
                                    "Action": [
                                        "acm-pca:CreateCertificateAuthority",
                                        "acm-pca:IssueCertificate",
                                        "acm-pca:GetCertificate"
                                    ],
                                    "Resource": {
                                        "Fn::Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
                                    }
                                } 
                            ]
                        }
                    }
                ]
            }
        }
    }
}
```

I used the following rule and it worked as intended:
`AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource == {"Fn::Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"}`

I am just wondering if I could do something with regular expression like
`AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource == {/.+Sub/: "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"}`

or 
`AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource == {"/.+Sub/": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"}`

to match the use cases below:
```
- "Resource": {
    "Fn::Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
}
- "Resource": {
    "!Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
}
```
Or a rule like the one below would not return any finding
`AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource == {"Fn::Sub": "/.+\${AWS::Region}:\${AWS::AccountId}.+/"}`

I am just wondering if I am using the right syntax or if I am missing something.

Thank you

**Comment by bstzahi** [comment]
+1 Regex support will be great for complicated conditions

**Comment by jotompki** [comment]
We are providing enhanced property access feature in the next release of the tooling, as detailed in #115. We hope to encourage users to do these checks using the KEYS operator to avoid using regular expression inside of json. So instead of 

```
AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource == {/.+Sub/: "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"}
```
one could write in the new version of the rules language
```
AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource KEYS == /.+Sub/
AWS::IAM::Role Policies.*.PolicyDocument.Statement.*.Resource.* ==  "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
}
```
As of now, we have no plan to support regular expression for json keys as listed above.

**Comment by dchakrav-github** [comment]
With Guard 2.0 you can select keys for a map that match a regular expression. The above rule in 2.0 is as follows 

```
AWS::IAM::Role Properties {
    Policies.*.PolicyDocument.Statement.*.Resource[ KEYS == /.+Sub/ ].* == "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
}
```
It would work for example given. However, it isn't correct as written. For `AWS::IAM::Role` the `Resource` attribute is [multi-valued](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html) or in other words is an array of values. It is possible to have any of the following specified in a CFN template 

```JSON
"Resource": [
  {
      "Fn::Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
  },
  "aws:arn...."
]
```
or 
```JSON
"Resources": "aws:arn...."
``` 
or 
```JSON
"Resources": ["aws:arn...", "aws:arn"]
```

Here you are only interested in targeting those that contain a `Fn::Sub` reference. Here is the way to specify this in Guard 2.0 

```
AWS::IAM::Role Properties {
    # 
    #  Select all Resource elements that have 'Fn::Sub'
    # 
    let resources = Policies.*.PolicyDocument.Statement.*.Resource[ 'Fn::Sub' EXISTS ]
    when %resources !EMPTY {
        %resources.* == "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
    }
}
```
How do we know if the rule really worked? You can unit test this rule with Guard 2.0.  Here is a sample test suite
 
```YAML
- input:
    Resources:
      role:
          Type: AWS::IAM::Role
          Properties: 
             Policies:
                 - PolicyDocument:
                     Statement:
                         - Resource: "aws:arn"
  expectations:
    rules:
        default: SKIP
- input:
    Resources:
      role:
          Type: AWS::IAM::Role
          Properties: 
             Policies:
                 - PolicyDocument:
                     Statement:
                         - Resource:
                             "Fn::Sub": "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"
  expectations:
    rules:
        default: PASS
- input:
    Resources:
      role:
          Type: AWS::IAM::Role
          Properties: 
             Policies:
                 - PolicyDocument:
                     Statement:
                         - Resource:
                             - "Fn::Sub": "fail"
                             - "*"
  expectations:
    rules:
        default: FAIL
- input:
    Resources:
      role:
          Type: AWS::IAM::Role
          Properties: 
             Policies:
                 - PolicyDocument:
                     Statement:
                         - Resource:
                             - "aws:arn"
                             - "*"
  expectations:
    rules:
        default: SKIP

```


We are internally tracking a feature where this expression would simplify to 
```
AWS::IAM::Role Properties {
    Policies.*.PolicyDocument.Statement.*.Resource[ 'Fn::Sub' EXISTS ].* ==  "arn:aws:acm-pca:${AWS::Region}:${AWS::AccountId}:certificate-authority/as"   
}
```
where it SKIPs the results if there are no such Resources present. For now, we need to use the `when !EMPTY` condition check.
