### ISSUE TITLE
[Enhancement] Provide GitHub action

### ISSUE THREAD

**Issue by thomasklinger1234** [aws-cloudformation/cloudformation-guard#93]
**Is your feature request related to a problem? Please describe.**
We use GitHub actions a lot to ensure code style and compliance. A pre-built GitHub action would be awesome as it encapsulates running, configuration and installation of `cfn-guard`. 

**Describe the solution you'd like**

The following configuration would be used in `.github/workflows/cfn-guard.yml`

```yaml
---
name: pullrequest
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-cloudformation/cloudformation-guard
        with:
          ruleset: "tools/cfn-guard/configuration/default.rules" # folder where rules reside
          templates: "cloudformation/*.template.yaml"
```

Open questions here:

- how to check dynamic generated templates (e.g. by AWS CDK or other generators)?

**Describe alternatives you've considered**
Using the pre-commit check from #22 and then a dedicated action for it.
