### ISSUE TITLE
[Enhancement] Support Variable substitution in JSON objects.

### ISSUE THREAD

**Issue by jmnarloch** [aws-cloudformation/cloudformation-guard#96]
**Describe the bug**
It appears that it's impossible to use variables in nested JSON structures at the moment for the cfn-guard command.

**To Reproduce**
Please supply:

1. An example rule set and template that results in the error
1. The commands you used to invoke the tool
1. The output of a `-vvv` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the lambda

**NOTE: Please be sure that the templates, rule sets and logs you provide as part of your bug report do not contain any sensitive information.**

I had created a template as follows:

```
let encryption_flag = true
AWS::DynamoDB::Table SSESpecification == {"SSEEnabled":%encryption_flag}
```

Evaluated against resource definition:

```
Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "MyTable"
      BillingMode: PROVISIONED
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Album"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"
      SSESpecification:
        SSEEnabled: true
```

Running command:

```
fn-guard check -r rule.ruleset -t template.yml
```

Yields error

```
[MyTable] failed because [SSESpecification] is [{"SSEEnabled":true}] and the permitted value is [{"SSEEnabled":%encryption_flag}]
Number of failures: 1
```

**Expected behavior**
The substitution of variable in JSON object works correctly.

**Screenshots**
N/A

**Operating System:**
MacOS

**OS Version**
10.15.7

**Additional context**
